scylladb/argus

argus/db/testrun.py, setup.py, tests/test_threaded_test_run.py
This makes sure that TestRun.shutdown method blocks until the heartbeat
thread exits, ensuring that it doesn't end up in a partially finished
state.
[Trello](https://trello.com/c/TRMUFXJw/4137-argus-keeps-threads-open-at-the-end-of-sct-test)
=> fix(argus.db.testrun): Wait until heartbeat thread shuts down

argus/db/interface.py, argus/db/testrun.py, setup.py, tests/test_db_interface.py, tests/test_e2e_argus.py
This is a migration commit, it requires a migration to be performed.
Due to this fact, the _TABLE_NAME was changed to test_runs_v2 and
migration was performed to migrate old data.
=> refactor(argus.db): Drop all clustering keys from TestRun

setup.py
Fixes `argus.db` not being installed in non-editable installs
=> fix(setup.py): Explicitly specify packages to install

argus/backend/argus_service.py, argus/backend/assets/Github/GithubIssue.svelte, argus/backend/assets/ReleaseDashboard/ReleaseActivity.svelte, argus/backend/assets/ReleaseDashboard/TestPopoutSelector.svelte, argus/backend/assets/TestRun/ActivityTab.svelte, argus/backend/assets/TestRun/NemesisData.svelte, argus/backend/assets/TestRun/ResourcesInfo.svelte, argus/backend/assets/TestRun/TestRun.svelte, argus/backend/assets/TestRun/TestRunComments.svelte, argus/backend/assets/TestRun/TestRunInfo.svelte, argus/backend/assets/WorkArea/Test.svelte, argus/backend/assets/WorkArea/TestRuns.svelte
This commit improves user experience when investigating runs, enforcing
that every timestamp uses UTC timezone and ISO format
[Trello](https://trello.com/c/P01aWk6E/4407-timestamps-should-be-consistent-use-utc-for-all)
=> fix(argus_web): Force UTC Timezone and ISO format in all timestamps

argus/backend/assets/WorkArea/TestRuns.svelte
TestRuns panel now marks builds that are currently open with blue
outline around the build button.
[Trello](https://trello.com/c/WVvtFlyO/4387-mark-builds-that-are-currently-opened)
=> improvement(TestRuns.svelte): Mark open Test Run cards with outline

argus/backend/assets/TestRun/IssueTemplate.svelte
Previously Issue Template showed all nodes left at the end of the run,
including loaders and monitors, which are not needed in an issue report.
[Trello](https://trello.com/c/R8aF9CSw/4388-remove-loader-nodes-and-monitoring-node-details-from-issue-template)
=> fix(IssueTemplate.svelte): Filter out monitor and loader nodes

argus/db/config.py, argus/db/interface.py, argus/db/testrun.py
This commit tidies up logging facilities within argus to always use
module-scope logger instead of class or other scope
[Trello](https://trello.com/c/bEQpmUb7/4482-remove-specific-logger-for-testrun-and-use-name-instead)
=> fix(argus.db): Use module scope logger instead of class scope

argus/backend/assets/Stores/TestRunsSubscriber.js, argus/backend/assets/TestRun/TestRun.svelte, argus/backend/assets/WorkArea/RunGroup.svelte, argus/backend/assets/WorkArea/RunRelease.svelte, argus/backend/assets/WorkArea/Test.svelte, argus/backend/assets/WorkArea/TestRuns.svelte, argus/backend/assets/WorkArea/TestRunsPanel.svelte, argus/backend/assets/WorkArea/WorkArea.svelte
This commit adds a couple of ways to remove unneeded runs, either by
clicking trashcan button on the runs collapse itself, or by clicking on
the test name again in the work area sidebar. Additionally, this commit
will add resource release handling to prevent memory leaks when runs are
removed from work area.
[Trello](https://trello.com/c/8AEjgcwI/4383-add-ability-to-remove-the-test-from-the-working-area)
Must be merged before #17
=> feature(WorkArea.svelte): Ability to remove runs from work area

argus/backend/assets/WorkArea/TestRunsPanel.svelte
This commit changes the display behaviour of runs being added to the
work panel to use reverse order, so that the newest test is going to be
displayed on top of the stack, instead of the bottom
[Trello](https://trello.com/c/vKbZnXv3/4492-show-test-details-on-top-when-clicking-on-the-test-in-the-sidebar)
Must be merged after #16
=> fix(TestRunsPanel.svelte): Order runs in reverse insertion order 

argus/backend/assets/Debug/FlashDebugComponent.svelte, argus/backend/assets/Github/GithubIssues.svelte, argus/backend/assets/ReleasePlanner/ReleaseScheduler.svelte, argus/backend/assets/TestRun/IssueTemplate.svelte, argus/backend/assets/TestRun/TestRun.svelte, argus/backend/assets/TestRun/TestRunComments.svelte, argus/backend/assets/WorkArea/WorkArea.svelte
This removes all "success" alert toasts, as they are not needed and
actively harm user experience
[Trello](https://trello.com/c/s4FYuzh0/4490-remove-success-notifications-popups)
=> fix(Alert.svelte): Remove "success" sendMessage calls

argus/backend/assets/WorkArea/TestRuns.svelte
Changes blue outline indicator around a run to instead be darker
shade of the current run status and inserts a finger post arrow to
provide a good indicator of a selected run
[Trello](https://trello.com/c/udOI67XN/4496-use-focus-instead-of-outline-when-clicking-on-multiple-testruns)
=> improvement(TestRuns.svelte): Better selected run indicator

argus/backend/assets/TestRun/TestRunInfo.svelte
[Trello](https://trello.com/c/OJ8B0R8e/4384-link-to-build-job-should-be-opened-in-new-tab)
Must be merged after #19
=> fix(TestRunInfo.svelte): Open build job url in a new window

argus/backend/assets/Common/TestStatus.js, argus/backend/assets/Common/TextUtils.js, argus/backend/assets/TestRun/NemesisTable.svelte, argus/backend/assets/TestRun/TestRun.svelte, package.json, yarn.lock
This commit adds a new nemesis viewer which is intended to replace old
proof of concept one. It presents itself as a table and has following
features: Sorting by column in ascending or descending order, Filtering
by column value and an ability to open a specific row for additional
information, like stack trace, skip reason, duration and affected node
information.
[Trello](https://trello.com/c/exZDw3au/4406-nemesis-tab-v2)
**Demo**
https://user-images.githubusercontent.com/7761415/149793369-e2fe6d6e-f86e-4586-bff0-a8fb8498d40a.mp4
=> feature(NemesisTable.svelte): New Nemesis Viewer

argus/backend/assets/WorkArea/TestRuns.svelte
[Trello](https://trello.com/c/L9X4nNzn/4542-replace-trash-icon-by-x-close-button)
=> fix(TestRuns.svelte): Use btn-close instead of fas-Trash icon

argus/backend/assets/TestRun/TestRun.svelte
[Trello](https://trello.com/c/AetV0ROs/4533-make-build-id-button-grayish-instead-of-black)
=> fix(TestRun.svelte): Use light background for build number indicator

argus/backend/assets/TestRun/IssueTemplate.svelte, argus/backend/assets/TestRun/TestRunInfo.svelte, argus/db/db_types.py, argus/db/interface.py, argus/db/testrun.py, setup.py, tests/conftest.py, tests/test_db_interface.py, tests/test_testinfo.py
Add missing build_id field into PackageVersion UDT that tracks build id
of the package being submitted.
[Trello](https://trello.com/c/5bpcgROU/4494-show-correct-scylla-version)
=> feature(db_types): Add build_id field to PackageVersion

argus/backend/assets/TestRun/Screenshots.svelte, argus/backend/assets/TestRun/TestRun.svelte, argus/db/testrun.py, tests/conftest.py, tests/test_testinfo.py
This PR adds suport for submitting screenshots alongside test run.
Accessible as part of TestRunResults, they are represented as a list of
strings, each string implicitly being a URL pointing to the location of
the screenshot. Also, it adds a screenshot viewer to the TestRun card, allowing to
view on a grid screenshots submitted as part of the run. Clicking the
screenshot would open a modal window in full size, allowing viewing and
downloading.
[Trello](https://trello.com/c/CjxNoE9l/4414-add-screenshots-links-to-the-details-of-the-run)
[Demo](https://user-images.githubusercontent.com/7761415/151021172-9816667c-8e77-4f99-b0ad-0b0c960da887.mp4)
=> feature(argus.db): Screenshots support

argus/backend/api.py, argus/backend/argus_service.py, argus/backend/assets/Common/TestStatus.js, argus/backend/assets/ReleaseDashboard/ReleaseDashboard.svelte, argus/backend/assets/ReleaseDashboard/TestPopoutSelector.svelte, argus/backend/assets/Stats/ChartStats.svelte, argus/backend/assets/Stats/ReleaseStats.svelte, argus/backend/assets/Stats/TestMapStats.svelte, argus/backend/assets/TestRun/TestRun.svelte, argus/backend/assets/release-page.js, argus/backend/event_processors.py, argus/backend/models.py, argus/backend/templates/release_dashboard.html.j2, argus/backend/templates/releases.html.j2, argus/db/db_types.py, argus/db/testrun.py, tests/test_e2e_argus.py
This PR adds an investigation status field to main TestRun object
allowing to track whether or not run was investigated / triaged after
completion.
Also, a new release dashboard has been added. This dashboard sorts tests by their group, shows issue /
investigation icons on each test if their status is not positive and
allows to quickly see last builds and open issues for each test by
clicking on them.
Image:
[Trello](https://trello.com/c/ecG2a9kz/4497-add-investigated-test-run-status)
=> feature(argus.db): Investigation status 

argus/db/cloud_types.py, argus/db/interface.py, argus/db/testrun.py, setup.py, tests/conftest.py
Due to the way TestResources.from_row worked before, it was possible to
end up with duplicate objects of the same resource, because the
constructor was reinstanting each object from 3 arrays, 2 of which
contained references to the first array. This is now fixed.
=> fix(argus.db.testrun): TestResources from_row constructor rework

argus/backend/assets/ReleaseDashboard/ReleaseActivity.svelte
This prevents errors when release activity wasn't fetched in time.
=> fix(ReleaseActivity.svelte): Replace placeholder raw_events value

argus/backend/assets/WorkArea/WorkArea.svelte
This commit adds a fixed 960px height for the sidebar in the work area
intended to improve user experience when selecting multiple tests
without them having to scroll constantly up or down each time they
select a test.
[Trello](https://trello.com/c/9Csu1cap/4410-test-runs-panel-should-be-anchored-to-the-viewport)
=> improvement(WorkArea.svelte): Limit work area sidebar height

argus/db/db_types.py
Adds a new terminated state which is used when a nemesis is terminated
by the test framework due to various reasons.
[Trello](https://trello.com/c/eeLFaug8/4567-create-terminated-state-for-nemesis)
=> improvement(argus.db.db_types): Add TERMINATED Nemesis state

argus/backend/argus_service.py, argus/backend/assets/Stats/TestMapStats.svelte
Adds a comment speech bubble to a test which has a comment attached to
it.
[Trello](https://trello.com/c/5U2En2WU/4626-add-comments-icon-to-the-release-dashboard)
=> improvement(TestMapStats.svelte): Show a comment speech bubble

argus/db/cloud_types.py, argus/db/testrun.py, tests/conftest.py, tests/test_cloud_types.py, tests/test_e2e_argus.py, tests/test_testinfo.py
This commit reworks resource tracking to instead use a singular list
and adds several additional fields to CloudInstanceDetails and
CloudResource classes. Specifically, it adds time_to_live to instance
details, allowing argus to infer whether or not a leftover resource was
probably terminated at that point and it adds a resource_type field to
CloudResource to help with matching node with cloud setup fields.
[Trello](https://trello.com/c/LnFRKGxd/4052-track-clean-resources-state-in-argusdb)
=> feature(argus.db): Resource tracking rework

argus/db/testrun.py
This replaces generic mechanism for updates with a manual query,
during heartbeat updates. Due to the fact that client application might
get stuck, but might update TestRun data in another part of the system,
the stuck heartbeat thread might override said data in this case.
This is now fixed
[Trello](https://trello.com/c/Bor1fUgt/4621-heartbeat-shoouldnt-override-the-data-when-test-is-stuck-and-we-moved-to-another-staged-in-jenkins-job)
=> fix(argus.db.testrun): Heartbeat only updates heartbeat

argus/backend/assets/TestRun/TestRun.svelte
This commit adjusts the background, margins and shadow of a TestRun
card. This should help with visibility and assist with distinguishing
individual test runs.
[Trello](https://trello.com/c/Xr7Vl1JN/4661-test-runs-should-be-more-easily-distinguished)
=> improvement(argus.frontend/TestRun.svelte): Improve card visibility

argus/backend/argus_service.py, argus/backend/assets/Profile/JobsList.svelte, argus/backend/assets/Profile/ProfileJobs.svelte
This commit revises the way assigned jobs are presented to the user
on the profile jobs page. First, the jobs are split into "Investigated"
and "Not Investigated" categories, with succesfully passed jobs
automatically being added to "Investigated" ones. Second, the jobs are
filtered server-side to only apply to current schedule + 1 week behind.
Lastly, a new "filter by name" control was added to simplify looking for
specific jobs
[Trello](https://trello.com/c/hRI4a2hR/4658-my-jobs-page)
=> feature(argus.backend): Profile Jobs tab v2

argus/backend/__init__.py, argus/backend/api.py, argus/backend/argus_service.py, argus/backend/assets/Common/StateManagement.js, argus/backend/assets/ReleaseDashboard/TestPopoutSelector.svelte, argus/backend/assets/Stats/TestMapStats.svelte, argus/backend/assets/TestRun/TestRunInfo.svelte, argus/backend/assets/WorkArea/RunGroup.svelte, argus/backend/assets/WorkArea/Test.svelte, argus/backend/assets/WorkArea/TestRuns.svelte, argus/backend/assets/WorkArea/TestRunsPanel.svelte, argus/backend/assets/WorkArea/WorkArea.svelte, argus/backend/build_system_monitor.py, argus/db/models.py, argus/db/testrun.py, requirements_web.txt
This PR adds a build system monitor and a specific implementation
for Jenkins. The intention is to monitor Jenkins releases and update
Argus metadata tables when there are missing tests. It also reworks 
theway the stats for runs are gathered and displayed,
the group field is now used to collect runs by group, since tests can
now have the same name across different groups.
[Trello](https://trello.com/c/aDyI6n3Y/4257-add-group-and-test-name-to-all-test-yamls)
=> Build system release tracking

argus/db/testrun.py, setup.py, tests/test_e2e_argus.py
Previously, heartbeat thread used a concatenated statement to update
heartbeat value, this is changed now to a BoundStatement to bring it in
line with other parts of argus.db interface. This also corrects an issue
with marker used for placeholder value, since '?' is not understood as a
placeholder in a non-prepared statement
=> fix(argus.db.testrun): Use prepared statements for heartbeat updates

argus/db/testrun.py, tests/test_e2e_argus.py
Since https://github.com/scylladb/argus/commit/36d7e51d95e7f3ec94cb6d5739933eb279137228 it is possible to run
into a name collision between tests, so tests that were scheduled using
duty planning now use a convention of "group/test_name" to avoid such
collisions. This fix is addressing the auto-assignment logic of TestRun
to also use such convention when looking for valid schedules.
[Trello](https://trello.com/c/6eBrOJxy/4753-auto-assignment-doesnt-work-after-changes-to-release-planning)
=> fix(argus.db.testrun): Use new scheduled test naming format 

argus/backend/argus_service.py
This fixes an issue where schedules created for release duty were not
visible on the "My Jobs" page
[Trello](https://trello.com/c/YdZQywi0/4762-my-jobs-page-uses-outdated-schedule-naming-convention)
=> fix(argus.backend.argus_service): Use new naming convention for my jobs

argus/backend/argus_service.py
This commit adds a way to show manually (that is, assigned without a
schedule) assigned jobs that are at most 1 month old.
[Trello](https://trello.com/c/O7WHA32K/4761-verify-that-manual-assignments-show-up-on-my-jobs-page)
=> improvement(argus.backend): Show manually assigned jobs on My Jobs page

argus/backend/assets/Profile/ProfileSchedules.svelte
[Trello](https://trello.com/c/QDU7PvT0/4772-add-jenkins-url-for-jobs-in-my-schedule-page)
=> improvement(ProfileSchedules.svelte): Show Jenkins and Workspace URLs

argus/backend/assets/ReleasePlanner/ReleasePlanTable.svelte
This commit adds an indicator to ReleasePlanTable which shows a dot
indicating last status of a test.
[Trello](https://trello.com/c/lPHOkmRp/4775-add-last-test-run-status-to-the-release-planning-page)
=> improvement(ReleasePlanTable.svelte): Display test status

argus/backend/argus_service.py, argus/backend/assets/ReleasePlanner/DutyPlanner.svelte, argus/backend/assets/ReleasePlanner/Schedule.svelte, argus/backend/assets/ReleasePlanner/ScheduleTable.svelte, argus/backend/assets/Stores/AssigneeSubscriber.js, argus/backend/assets/WorkArea/RunGroup.svelte, argus/backend/assets/WorkArea/Test.svelte
This commit adds display of assignees to invidual tests in line with
their respective schedules defined in Release Planner.
[Trello](https://trello.com/c/ELd1kWBJ/4771-assignees-not-shown-in-work-area-for-release-50)
=> improvement(argus.backend): Show assignees for individual jobs

argus/backend/argus_service.py
Removes obsolete substitution logic that was previously used
to strip test name of a suffix inside it.
[Trello](https://trello.com/c/UVrc1jUQ/4809-api-error-when-pasting-in-github-issue-link-in-dashboard-run-issues-tab)
Fixes #59
=> fix(argus_service.py): Remove obsolete regex substituion

argus/backend/assets/TestRun/TestRunInfo.svelte
This commit adds an ssh field to the run details, allowing quick ssh
connections to be established
[Trello](https://trello.com/c/nxl7gox6/4773-add-ssh-command-to-connect-to-the-sct-runner-in-details-tab)
=> improvement(TestRunInfo.svelte): Show an SCT Runner field during runs

argus/backend/assets/TestRun/TestRun.svelte, argus/backend/assets/TestRun/TestRunInfo.svelte, argus/backend/assets/WorkArea/RunRelease.svelte, argus/backend/assets/WorkArea/TestRuns.svelte, argus/backend/assets/WorkArea/WorkArea.svelte, argus/backend/assets/argus.css, argus/backend/templates/base.html.j2, argus/backend/templates/profile.html.j2, argus/backend/templates/test_runs.html.j2
This commit adds a sticky indicator to a TestRuns accordion, which shows
when the header of said accordion moves outside the viewport. To reduce
visual clutter, the area also received slight color adjustment and
removal of most unneeded borders. Additionally, the build number buttons
now scroll towards open run instead of closing it, and closing was moved
onto the card itself as its own separate button.
[Trello](https://trello.com/c/450qC6kD/4660-anchor-test-run-info-title-and-builds-when-scrolling-down)
Demo:
https://user-images.githubusercontent.com/7761415/159334679-4a4c5cc8-a6b6-45a0-86c1-05df36de957f.mp4
=> feature(TestRuns.svelte): Viewport run indicator

argus/backend/assets/ReleaseDashboard/TestPopoutSelector.svelte
This changes the behaviour of TestPopoutSelector to be sticky once
scrolled down, allowing easier track of what's selected on the test map
[Trello](https://trello.com/c/VYdB1paH/4770-anchor-selected-runs-in-release-dashboard)
Demo:
https://user-images.githubusercontent.com/7761415/159343386-59ceb5da-ea38-4f69-b4d0-69b716f820a8.mp4
=> improvement(TestPopoutSelector.svelte): Sticky selector

argus/backend/argus_service.py, argus/backend/assets/ReleaseDashboard/TestPopoutSelector.svelte, argus/backend/assets/Stats/TestMapStats.svelte, argus/backend/assets/WorkArea/AssigneeList.svelte
This commits adds assignees icons to selected tests in
TestPopoutSelector, much like assignee icons in the Work Area.
[Trello](https://trello.com/c/3ULVTqWG/4818-show-assignee-in-release-dasboard-when-clicked-on-run)
=> improvement(TestPopoutSelector.svelte): Show assignees for tests

argus/backend/assets/ReleaseDashboard/ReleaseDashboard.svelte, argus/backend/assets/ReleaseDashboard/TestPopoutSelector.svelte, argus/backend/assets/Stats/ReleaseStats.svelte, argus/backend/assets/Stats/TestMapStats.svelte, argus/backend/assets/WorkArea/AssigneeList.svelte
This commits bring a new redesign to the release dashboard, focusing on
TestMapStats component, changing it from a heat-map like design to a
card design. Tests are now sorted by status, include the name and
current assignees icons.
[Trello](https://trello.com/c/rIE5y7qM/4853-redesign-release-dashboard)
=> feature(TestMapStats.svelte): Release Test Map redesign

argus/backend/assets/TestRun/ResourcesInfo.svelte
This commit adds two new columns to resources information of a test run
card, which display Public and Private IP addresses.
[Trello](https://trello.com/c/RxzZZ0DQ/4831-add-ip-information-in-resources-tab)
=> improvement(ResourcesInfo.svelte): Display Public/Private IP addresses

argus/backend/assets/Stats/TestMapStats.svelte
This commit changes the behaiour of a test card to display last run's
assignee if it differs from people assigned to the test.
[Trello](https://trello.com/c/Dk2kTCBG/4864-show-test-run-assignee-on-test-card-if-it-differs-from-scheduled-assignee)
=> fix(TestMapStats.svelte): Display actual assignee if assigned

argus/backend/assets/ReleasePlanner/ReleasePlanTable.svelte, argus/backend/assets/ReleasePlanner/Schedule.svelte, argus/backend/assets/ReleasePlanner/ScheduleTable.svelte
This fixes an issue where a click on one of the schedule buttons would
cause schedule to close on Duty Planner table due to being parented to a
cell which contains an onClick handler.
[Trello](https://trello.com/c/niFvCoCh/4878-unable-to-edit-schedule)
=> fix(Schedule.svelte): Add a close button

argus/backend/argus_service.py
This fixes a problem where a user registering using github oAuth would
have "null" as their name due to them having no name specified in their
github profile
[Trello](https://trello.com/c/LiFbRTrZ/4880-null-user-name)
=> fix(argus_service.py): Use Github login if name isn't specified

argus/backend/assets/ReleaseDashboard/ReleaseDashboard.svelte, argus/backend/assets/ReleaseDashboard/TestPopoutSelector.svelte
This adds responsive breakpoints for both width (TestMapStats and
TestPopoutSelector) and height (TestPopoutSelector).
[Trello](https://trello.com/c/pVvTjImC/4883-adjust-columns-on-release-dashboard)
=> improvement(ReleaseDashboard.svelte): Responsive breakpoints for blocks

argus/backend/assets/Discussion/Comment.svelte
This fixes issues with browser theme preference set to dark.
=> fix(Comment.svelte): Let markdown parser handle background color

argus/backend/api.py, argus/backend/argus_service.py, argus/backend/assets/Common/TextUtils.js, argus/backend/assets/Github/GithubIssue.svelte, argus/backend/assets/Github/GithubIssues.svelte, argus/backend/assets/ReleaseDashboard/ReleaseDashboard.svelte, argus/db/models.py
This commit adds a way to fetch github issue state, labels to the
GithubIssue component, which is done client-side via first acquiring
User Oauth token from the server. It also changes issue display in
release dashboard, aggregating runs per unique issues, instead of issue
per run like it was previously.
[Trello One](https://trello.com/c/ADpZWAC6/4907-show-labels-in-all-issues-part-of-release-dashboard)
[Trello Two](https://trello.com/c/7uPRetcd/4897-release-dashboard-all-issues-add-run-info)
=> feature(argus.frontend): Github Issue state display

argus/backend/assets/Profile/ProfileJobs.svelte
This fixes a problem where ProfileJobs would hide jobs that have
"investigating" status from view.
=> fix(ProfileJobs.svelte): Filter "investigated" not "not_investigated"

argus/backend/controller/api.py
This commit changes behaviour of /release/stats endpoint to set a
max-age cache control header.
=> improvement(api.py): Cache stats requests

frontend/TestRun/IssueTemplate.svelte
This changes issue template back to normal selection behaviour, and adds
a button to select all text within issue template
[Trello](https://trello.com/c/EdqkPNAJ/4957-issue-template-allow-partial-copy-of-the-text)
=> improvement(IssueTemplate.svelte): Allow partial selection

argus/db/models.py
[Trello](https://trello.com/c/BlvNh4cv/4882-set-limit-for-comment-message-length)
=> fix(argus.db.models): Set comment message limit to 65535 bytes

frontend/Stats/TestMapStats.svelte
[Trello](https://trello.com/c/n7fCaoOn/5025-orange-square-for-in-progress-jobs-in-release-dashboard-the-eye-icon-isnt-that-clear)
=> fix(TestMapStats.svelte): Highlight tests that are being investigated

uwsgi.ini
To mitigate memory leaks, uwsgi.ini will now reload workers after either 24 hours of running or 2048 requests served.
=> fix(uwsgi.ini): Add max-worker-lifetime and max-requests settings

start_argus.sh
This addresses the problem where systemd would kill the entire service
when the "main" worker exits. Use of exec removes extra "bash" process
from the resulting CGroup
=> fix(start_argus): Use master process for uWSGI and replace bash shell

argus/backend/controller/api.py, argus/backend/controller/main.py, argus/backend/service/argus_service.py, frontend/Common/StateManagement.js, frontend/Profile/JobsList.svelte, frontend/Profile/ProfileSchedules.svelte, frontend/ReleaseDashboard/TestPopoutSelector.svelte, frontend/Stores/TestRunsSubscriber.js, frontend/Stores/WorkspaceStore.js, frontend/TestRun/TestRun.svelte, frontend/WorkArea/RunGroup.svelte, frontend/WorkArea/RunRelease.svelte, frontend/WorkArea/Test.svelte, frontend/WorkArea/TestRuns.svelte, frontend/WorkArea/TestRunsPanel.svelte, frontend/WorkArea/TestRunsSelector.svelte, frontend/WorkArea/WorkArea.svelte, frontend/test-runs-standalone.js, templates/profile_jobs.html.j2, templates/standalone_test_with_runs.html.j2, webpack.config.js
This commit refactors TestRuns component to instead depend only on
provided testId, fetching remaining information from backend. In
addition, this reworks sidebar to instead do lazy fetches on user
clicks, instead of trying to load everything at once. This also adds
TestRuns selector onto the Single Run page and onto the My Jobs page.
In addition, My Jobs page has received a slight redesign, intended to
help readability and to make it consistent.
[Trello](https://trello.com/c/XVLQWW0a/4955-show-all-runs-in-my-jobs-page)
=> feature(WorkArea.svelte): TestRuns selector & state refactor

frontend/Common/DateUtils.js, frontend/ReleasePlanner/DutyPlanner.svelte, frontend/ReleasePlanner/ReleaseScheduler.svelte
This commits adds support for using Duty (Group) planner for
non-perpetual (one-time) releases and Release (Test) planner for
perpetual releases. Currently, dates generated for one-time releases are
1 year backward for start time, 1 year forward for end time, this is
done because this commit does not include backend changes needed to
ignore start/end times for one-time releases. Group planner is currently
experimental for one-time releases as its table is unable to display
year-long schedule as of right now. It will display it on the start
date, which, being one year backward is awkward to locate.
[Trello](https://trello.com/c/sWwznFIL/5121-make-scheduler-aware-of-the-weekly-release-scheduler)
=> feature(release/duty planner): Support universal usage

argus/backend/service/argus_service.py, frontend/Discussion/MarkedMentionExtension.js
[Trello](https://trello.com/c/6PrnW1ut/5166-notifications-manager-ignores-users-with-capital-letters-in-the-name)
=> fix(ArgusNotification): Check capital letters in username regex

argus/backend/service/argus_service.py, frontend/WorkArea/Test.svelte
This fixes an issue where schedules assigned by test would still be
shown after expiring. Additionally, it fixes an issue where an outdated
schedule would be displayed after expiring for the remainder of Mon-Sun
week because it was using monday of that week as a pivot point. This was
replaced with current date, to match every other instance of getting
current schedules.
[Trello](https://trello.com/c/KJzDlOVi/5175-outdated-schedules-are-being-displayed)
=> fix(argus_service.py): Filter outdated group/test schedules

frontend/Discussion/Comment.svelte, frontend/Discussion/CommentEditor.svelte, frontend/TestRun/TestRunComments.svelte
This commit fixes an issue where comments collection would be refreshed
during editing, causing state to reset and edited data to be lost.
Fixes #142
=> fix(TestRunComments.svelte): Do not fetch during editing

frontend/TestRun/TestRunInfo.svelte
This PR adds a fallback in case Argus isn't running in secure
context (that is, HTTPS) by providing hydra commands as selectable text
instead of buttons that automatically copy text into clipboard
Fixes #143
Screenshot demonstrates both the buttons and fallback input fields for posterity
=> fix(TestRunInfo.svelte): Display text if clipboard isn't available

frontend/Common/RunUtils.js, frontend/TestRun/TestRunInfo.svelte
Adds an "Upgraded scylla version" field to the test run card, visible
when packages field contains a scylla-server-upgraded package. Renames
normal "Scylla Version" field to "Base scylla version" field if that's
the case.
=> improvement(TestRunInfo.svelte): Show upgraded scylla version

argus/backend/controller/auth.py, argus_web.example.yaml
This fixes an issue where private repositiories' issues could not be
read due to missing 'repo' scope. This commit also adds a config
property to override default github scopes\
Fixes #110 
[Trello](https://trello.com/c/ArkIaxcr/4980-argus-failing-to-get-state-of-enterprise-issues)
=> fix(controller/auth.py): Configurable scopes and addition of repo scope

frontend/WorkArea/TestRuns.svelte, frontend/WorkArea/TestRunsSelector.svelte
This adds a close buttons to the selector pills, allowing quicker
closing of opened runs.
Task: scylladb/qa-tasks#780
=> feature(TestRunsSelector.svelte): Show close button for open cards

frontend/Common/RunUtils.js, frontend/TestRun/IssueTemplate.svelte
This commit adds info about relocatable package to issue template. It gets this info from `Packages` in `test_runs` table.
implements: https://github.com/scylladb/argus/issues/120
=> feature(issue_template): add relocatable pkg to issue template

argus/backend/controller/api.py, frontend/ReleaseDashboard/TestDashboard.svelte, frontend/Stats/ReleaseStats.svelte, frontend/Stores/SingleTestRunSubscriber.js, frontend/Stores/TestRunsSubscriber.js, frontend/WorkArea/RunRelease.svelte
This should alleviate the load on the particularly heavy requests such as stats and remove needless refreshing on the workspace page.
=> fix(frontend): Increase polling times for stat and testrun refreshes

frontend/ReleaseDashboard/TestPopoutSelector.svelte
This fixes an issue where identically named tests would overwrite each other in the selector and statuses.
=> fix(TestPopoutSelector.svelte): Use correct iteration key

argus/backend/plugins/sct/controller.py, argus/backend/plugins/sct/service.py
Per @tarzanek request this adds an endpoint that contains kernels used during runs in SCT. The report JSON contains kernels used for each version, and in a separate object, for each kernel, quick stats for it - passes, failures, aborts.
=> feature(sct plugin): Kernels by Scylla Version API Endpoint

argus/db/config.py, argus/db/interface.py
Since we are using public addresses, to connect from client directly, scylladb/python-driver#185 surfaced that we are connecting only to one node, and it's not exactly
how the driver is intend to be working (we do all the tests updates work on one specific node, and we should do is on all of them)
Ref: https://github.com/scylladb/python-driver/pull/185
=> Switch to use `AddressTranslator` for client connection

argus/backend/service/argus_service.py, argus/backend/service/stats.py
Mitigates an issue where build numbers overflow and start from beginning leading to stats reporting ancient runs instead of new ones.
=> fix(service/stats.py): Sort last runs by timestamp and build_number

frontend/Profile/JobsList.svelte
This fixes pagination numbers going offscreen instead of wrapping to the next line
Fixes #192
=> fix(JobsList.svelte): Wrap the flexbox for page numbers

argus/backend/controller/api.py, frontend/WorkArea/TestRuns.svelte
This change will allow any user to select a plugin (test) type for a test entity
Task: scylladb/qa-tasks#1050
=> improvement(TestRuns.svelte): Allow any user to to select test type

frontend/TestRun/IssueTemplate.svelte
Fixes an issue where template text would contain safe placeholder entities like &lt; when it was not needed
Task: scylladb/qa-tasks#942
=> fix(IssueTemplate.svelte): Write text to clipboard and not escaped HTML

argus/backend/controller/testrun_api.py, argus/backend/service/testrun.py
This change adds an endpoint to the TestRun API allowing a periodic cleanup
of "stuck", i.e. runs that have not had their heartbeat updated for more than
45 minutes. The endpoint call will set them as "ABORTED" in such case.
Task: scylladb/qa-tasks#940
=> feature(scripts): Stuck runs remover

argus/backend/plugins/sct/testrun.py
This fixes an issue where client would receive a DoesNotExist exception
when submitting an sct run to the server
=> fix(plugins.sct): Handle DoesNotExist for assignee getter

argus/client/base.py
This fixes an issue where backend replies with non-standard exception
(can happen when such exception is unhandled on the backend side).
=> fix(argus.client.base): verify response parameters in check_response

frontend/ReleaseDashboard/ReleaseDashboard.svelte, frontend/ReleaseDashboard/TestDashboard.svelte
This improvement adds a way for a user to save/share a specific version
of the release dashboard. By clicking on the version button, the version
is saved into the url, allowing the selection to persist between
refreshes and different sessions.
Closes #205
Must be merged after #215
=> improvement(ReleaseDashboard.svelte): Store product version in the qs

frontend/TestRun/Event.svelte, frontend/TestRun/EventsTab.svelte, frontend/TestRun/RawEvent.svelte, frontend/TestRun/StructuredEvent.svelte, frontend/TestRun/TestRun.svelte
This commits adds a rudimentary parser for the current text events
inside test run entities. The window is changed to allow better
organization - the events are now sorted by time on a single timeline
and can be individually hidden (by default, only Error and Critical
events are shown). The events can also be filtered by a substring inside
the displayed event message.
Demo:
https://user-images.githubusercontent.com/7761415/226166706-c6e66a4a-690c-4467-b811-91daa40f7d64.mp4
=> feature(EventsTab.svelte): Structured events and event parsing

frontend/WorkArea/TestRuns.svelte
If we can't retrieve runs due to missing the plugin name, we can't fix
the plugin name because the block for that is housed inside the runs
block, which needs runs to be drawn. This is now fixed
=> fix(TestRuns.svelte): Fix missing plugin selector

argus/backend/plugins/sct/testrun.py, scripts/migration/migration_2023-04-07.py
The migration script included in this commit will migrate all runs from
old test_runs_v8 table to the new one, ignoring any that have an empty
string primary key.
The commit also updates the backend table name to the new one.
Task: scylladb/qa-tasks#1043
Details about planned migration:
To facilitate argus cluster upgrade to 2022.2 we need to fix a repair problem currently affecting the cluster - some of the rows contain empty string primary key, preventing repair from fully completing. The idea of this migration is to just create a new table and move every run there. Planned window for it is on April 12th evening, which should provide a window to do the changeover  without affecting many (if any) runs currently in progress).
=> fix(argus): Add migration scripts required for cluster upgrade

frontend/Github/GithubIssue.svelte
This fix corrects an issue where a test run link on an aggregated issue
would use the old test_run endpoint, which has been deprecated and no
longer works as runs endpoint now requires a valid test_id in addition
to run_id.
=> fix(GithubIssue.svelte): Correct route for test runs

argus/backend/plugins/core.py, argus/backend/service/testrun.py, frontend/Github/GithubIssue.svelte
- fix(service.testruns): Fix single run retrieval by id
- improvement(GithubIssue.svelte): Store test_id in aggregated issues
=> GithubIssue and TestRunService fixes

frontend/Github/GithubIssues.svelte
This change adds issue title to the list of exported issues, and
additionally sorts them in ascending order based on issue number
=> improvement(GithubIssues.svelte): Show sorted issues with title

frontend/TestRun/EventsTab.svelte
This fix corrects an issue where due to operator precedence between ??
and + the " UTC" would not be concatenated if eventTimestamp field
is present on the event object, leading to timestamp being shifted to N
amount of hours due to being interpreted as a local timestamp, instead
of UTC one.
=> fix(EventsTab.svelte): Fix operator precedence in timestamp parsing

frontend/TestRun/IssueTemplate.svelte
This commit adds a link to the test run in the run issue template.
=> improvement(IssueTemplate.svelte): Add Argus run link

argus/backend/plugins/core.py
This fix is intended to correct older tests which may have been
created as "scylla-cluster-tests" plugin, instead of the plugin they
would be using in the future (or empty for this fix to work)
=> fix(plugins/core.py): Assign plugin if it doesn't match

argus/backend/plugins/driver_matrix_tests/model.py
Make scylla-version field as in to sync up with other types of runs we
have (previously we had been doing replacements in sct runs)
=> fix(driver_matrix_tests): Do not alter scylla_version

frontend/TestRun/DriverMatrixTestCollection.svelte
This change fixes an issue where a failed driver matrix test run could
show detailed breakdown as "Passed" if the cause of failures were errors
during the tests.
=> fix(DriverMatrixRun): Show collections with errors as failed

argus/backend/plugins/driver_matrix_tests/model.py, argus/client/driver_matrix_tests/client.py, pyproject.toml
This commit moves test status logic from client into backend and
additionally introduces additional logic to help determine final status.
Runs are now considered failed if they lack at least two submitted
results and are also considered failed if the runs lack at least one
'datastax' driver and one 'scylla' driver.
=> fix(driver_matrix_tests): Determine status server-side

argus/backend/plugins/sirenada/model.py, frontend/Common/TestStatus.js, frontend/TestRun/Sirenada/SirenadaTestBreakdown.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/WorkArea/TestRuns.svelte, package.json, templates/base.html.j2, yarn.lock
feature(frontend): Sirenada TestRun Card
Sirenada card now contains a special "Breakdown" tab, which contains
tests sorted by classname, then by browser. The card has following
helpers for investigations: ability to expand all failures at once,
screenshot viewing (currently only embedded), displaying the requests
file, and a link to an s3 bucket should a test contain any failures
Task: scylladb/qa-tasks#1120
- improvement(argus): Update frontend dependencies
- feature(frontend): Sirenada TestRun Card
=> Frontend components for Sirenada Runs

frontend/TestRun/Sirenada/SirenadaTestBreakdown.svelte
This fixes an issue where results would be incorrectly grouped by just
browser, mixing various cluster types
=> fix(SirenadaTestBreakdown.svelte): Aggregate by browser-cluster

argus/backend/controller/auth.py, argus/backend/controller/main.py, argus/backend/service/user.py
This commit improves UX when clicking on a link with an expired session -
previously user would get redirected to the login page and afterwards
would end up on their profile page. This is now fixed - the URL user was
going to is now preserved as a session variable and user gets redirected
to it on successful login (currently only on Github logins)
=> improvement(auth): Redirect user to the requested page on login

frontend/TestRun/DriverMatrixTestRun.svelte, frontend/TestRun/IssueTab.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/TestRun/TestRun.svelte
This change adjust the Issues tab to display both issues attached to
this particular run and a collapse of all issues associated with the
run's test.
Task: scylladb/qa-tasks#288
=> improvement(*TestRun): Allow viewing all issues relevant to the test

argus/backend/controller/api.py, argus/backend/controller/main.py, argus/backend/controller/team.py, argus/backend/controller/testrun_api.py, argus/backend/events/event_processors.py, argus/backend/models/web.py, argus/backend/plugins/core.py, argus/backend/service/argus_service.py, argus/backend/service/testrun.py, argus/backend/util/enums.py, argus_web.example.yaml, frontend/Common/TestStatus.js, frontend/Profile/ProfileJob.svelte, frontend/Profile/ProfileJobs.svelte, frontend/Profile/ProfileJobsTab.svelte, frontend/ReleaseDashboard/TestDashboard.svelte, frontend/Stats/NumberStats.svelte, frontend/Teams/TeamMember.svelte, frontend/TestRun/DriverMatrixTestRun.svelte, frontend/TestRun/RunInvestigationStatusButton.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/TestRun/TestRun.svelte, frontend/WorkArea/TestRunDispatcher.svelte, frontend/WorkArea/TestRuns.svelte, frontend/WorkArea/TestRunsSelector.svelte, frontend/profile-jobs.js, templates/profile_jobs.html.j2
This commit completely reworks "My Jobs", presenting only jobs that need
to be investigated and started in a tabbed interface. The runs are now
aggregated by the test, showing a short summary of items to be
investigated. Runs themselves are now only shown if they are at most 30
days old (configurable in the global config), and that's the only
condition, as the previous suite of conditions led to too many jobs
being shown to the user. The page now also includes set of filters to
filter jobs that are needed to be done - either by release branch or
product version. Finally, the "Done" tab shows runs that have been
marked as investigated in the current investigation session (shows
nothing by default, as that's no longer needed due to aggregation)
Additionally, a new "Ignore runs" feature has …
=> feature(ProfileJobs.svelte): Rework My Jobs page

frontend/TestRun/IssueTemplate.svelte
Fixes a crash where not yet submitted sct runner info would crash
browser js
=> fix(IssueTemplate.svelte): Add null coalescence to sct_runner_host

argus/backend/plugins/driver_matrix_tests/model.py
This change fixes an issue where CQL engine would stringify string Enum
as '<Enum.VALUE>' instead of casting it to string, causing CQL query to
error out.
Fixes: scylladb/argus#256
=> fix(driver_matrix_tests): Resolve Enum value manually

argus/backend/service/stats.py, argus/backend/service/testrun.py
This change addresses an issue where release dashboard would show failed
run, but not that failed run's investigation status (because of sorting
differences) and also makes sure to show the worst case investigation
status for aggregated runs. Additionally, this makes testrun endpoint to
sort runs by both build number and status, making aggregated runs show
the worst case status here too.
Task: scylladb/qa-tasks#1216
=> fix(stats.py): Always show worst case status and investigation status

argus/backend/plugins/driver_matrix_tests/model.py
This commit fixes an issue where a driver matrix run would never assign
a job to the scheduled user due to missing code
=> fix(driver_matrix_tests): Assign user to a job

frontend/TestRun/IssueTemplate.svelte
For issues relating to upgrade tests, it's important to specify the target version of the test run. As such, I added the target version to the issue template.
Solves #212
=> improvement(IssueTemplate): include the target scylla version for upgrade tests

frontend/ReleaseDashboard/TestDashboard.svelte
This changes sort order of the tests on the TestDashboard to
instead first sort by status and then by name of the test.
=> improvement(TestDashboard.svelte): Sort tests cards by status and name

argus/backend/service/stats.py
This adjusts behaviour as requested in scylladb/argus#273, making filter
also return jobs that have no version in case there was an issue with
retrieving that version during the run. The jobs are still sorted by
start time and only last 10 are presented
Closes #273
Task: scylladb/argus#273
=> fix(stats.py): Include unversioned runs in per-version filters

frontend/Common/TestStatus.js, frontend/TestRun/Sirenada/SirenadaTestBreakdown.svelte
For siren-tests plugin was added the number of failures of the job and the total results info 
fixes: https://github.com/scylladb/argus/issues/266
=> fix(siren-tests):  Add the number of failures info

argus/client/driver_matrix_tests/client.py, pyproject.toml
This fixes an issue where a C++ driver matrix test is always marked as
failed due to the filename regex not being compatible and ending up with
driver_name being null, where as at least one datastax and one scylla
result is required.
Task: scylladb/qa-tasks#1435
=> fix(argus.client): Add a pattern for CPP driver results

argus/backend/plugins/sct/controller.py, argus/backend/plugins/sct/plugin.py, argus/backend/plugins/sct/service.py, argus/backend/plugins/sct/testrun.py, argus/backend/plugins/sct/types.py, argus/backend/plugins/sct/udt.py, argus/backend/util/encoders.py, argus/client/sct/client.py, frontend/TestRun/ActivityTab.svelte, frontend/TestRun/SCTSubTests/Performance/PerformanceTabBodyComponent.svelte, frontend/TestRun/SCTSubTests/Performance/PerformanceTabComponent.svelte, frontend/TestRun/SCTSubTests/Subtest.js, frontend/TestRun/TestRun.svelte
This commit adds a support and frontend components for performance
regression jobs (throughput and latency). Initial frontend components
mimic the current email format for those jobs and regression finder
mimics the way sct finds a regression - A regression will be looked for
across all available version on which this job has been ran, until it
either finds the regression between best or last run. In this scenario,
SCT Plugin will set the job as failed and will create an event explaining
the cause for the failure and run the comparison failed against.
Task: scylladb/qa-tasks#1243
=> feature(plugins/sct): Add support for Performance Subtest

argus/backend/plugins/core.py, argus/backend/service/argus_service.py, frontend/ReleasePlanner/ScheduleTable.svelte
This fix corrects an issue where a large group of tests would cause a
query error due to exceeding the size of available cartesian product for
the query. Additionally this corrects an issue where deleting a schedule
without an assignee would be impossible.
=> fix(argus_service.py): Do not use IN query for querying unassigned runs

argus/backend/plugins/driver_matrix_tests/model.py
This PR fixes an issue with Python's versions before 3.11 handling
of iso format strings, where they would reject isoformatted timestamp if
it contains "Z" at the end, which is used to indicate that the timestamp
in question is located at UTC-0.
Fixes: #261
=> fix(driver_matrix_tests): Remove Z from timestamp if found

argus/backend/models/web.py
This change changes default release type to "Static", which is used for
scheduling purposes to determine if release needs weekly schedules (like
scylla-master for example) or endless static schedules like point
releases.
=> fix(models/web): Make default release non-perpetual

argus/backend/util/encoders.py, frontend/ReleaseDashboard/ReleaseActivity.svelte, frontend/ReleaseDashboard/TestDashboard.svelte
This fixes an issue on certain browsers where dates would fail to parse,
crashing the application.
Fixes #298
Fixes #194
=> fix(encoders.py): Always provide ECMAScript datetime for dates

frontend/ReleaseDashboard/ReleaseDashboard.svelte, frontend/Stats/NumberStats.svelte, frontend/Stats/ReleaseStats.svelte
This change adds a paramater to adjust displayed statuses inside the
widget (filtering out unneeded ones). Additionally it adds percentage
display to each status.
Fixes #295
=> improvement(NumberStats): Filtering for statuses and Percentages

frontend/WorkArea/TestRuns.svelte
This change adds a jenkins url to the system messages view (any state
when there are no runs available to display), simplifying finding job in
the CI.
Fixes #307
=> improvement(TestRuns.svelte): Add jenkins job url to system messages.

frontend/ReleaseDashboard/TestDashboard.svelte, frontend/Stats/NumberStats.svelte
This adds a status bar to release dashboard groups, similar to the
global job status bar visible on the release dashboard.
Fixes #301
=> improvement(TestDashboard): Display per-group status bars

argus/backend/plugins/sct/testrun.py
This fixes an issue where old versions of runs would encounter an API
error.
=> fix(plugins/sct): Mark new fields as optional

argus/backend/plugins/driver_matrix_tests/controller.py, argus/backend/plugins/driver_matrix_tests/plugin.py, argus/backend/plugins/driver_matrix_tests/service.py, docs/api_usage.md
feature(driver_matrix_tests): Endpoint for querying per-test driver results
This commit adds an endpoint to query driver matrix results per test (so
per driver type), by providing build_id we get a report that contains
all tested driver versions for this particular build id.
Closes #296
=> feature(driver_matrix_tests): Endpoint for querying per-test driver results

argus/backend/service/testrun.py, frontend/Profile/Login.svelte, frontend/login.js, templates/auth/login.html.j2, webpack.config.js
This change allows user to decline giving full repository read/write
permissions (as this is needed to read issue states inside organization
private repositories) via a checkbox on the login page. The state of the
checkbox is saved into local storage to prevent user from having to
constantly check it. Additionally, this commit moves the login page out
of a Jinja template and into a Svelte component.
Task: #297
=> feature(Login.svelte): Allow disabling `repo` scope for Github login

argus/backend/plugins/sct/testrun.py, frontend/TestRun/TestRunInfo.svelte
This change adds a new field to SCT runs allowing to track
stress_duration field. The field is provided when a run had overriden
its default duration - for example a 3h longevity could be specified to
run for 6h instead. This change allows user to see the new duration to
better understand why a particular run ran for a certain period of time.
Fixes #279
=> feature(plugins/sct): Store stress_duration in SCT runs

frontend/Github/GithubIssues.svelte, frontend/ReleaseDashboard/ReleaseDashboard.svelte
This change improves the way issues are presented in the issue view -
adding pagination for issue lists over 10 items, filtering bar to filter
issues by name, repo and number and ordering support - currently adding
Title, repo and Date (with ascending/descending orders)
Fixes #231
=> improvement(GithubIssues.svelte): Pagination, filtering and ordering support

frontend/TestRun/IssueTemplate.svelte
This change adjust the location of scylla and other packages in the SCT
issue template, moving the package information to the top into a new
section labeled "Packages".
Fixes #324
=> improvement(IssueTemplate.svelte): Move package information to the top

frontend/ReleaseDashboard/ReleaseDashboard.svelte, frontend/ReleaseDashboard/TestDashboard.svelte, frontend/Stats/ReleaseStats.svelte, frontend/Stats/StatsFetcher.svelte, frontend/TestRun/DriverMatrixTestRun.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/TestRun/TestRun.svelte, frontend/WorkArea/RunRelease.svelte, frontend/WorkArea/TestRunDispatcher.svelte, frontend/WorkArea/TestRuns.svelte, frontend/WorkArea/TestRunsSelector.svelte, frontend/release-page.js
This commit changes the way Argus fetches release statistics in
background. Primary changes include:
* Workarea no longer fetches all release stats, instead only fetching
release once when it is clicked. A button was added to refresh those
stats manually to the release dropdown.
* Release Dashboard was optimized to only make 1 stats request per state
change (version, background update) and now also contains a manual
refresh button.
* Auto-refresh timers, where still applicable, were increased to 15-20
minutes
* Background stats request will not fire now if the tab the request is
being made from is not in focus
* Updating test run status now also updates the run selector.
* Both TestRun and TestRunSelector now contain a manual refresh button.
Timers were increased for certain test types …
=> improvement(frontend): Background stats fetching rework

frontend/WorkArea/TestRuns.svelte
This change corrects an issue where TestRuns widget would not fetch runs
if it was open in a new tab - causing that tab to be instantly
backgrounded, preventing initial fetch from occuring.
=> fix(TestRuns.svelte): Ignore lack of focus on initial fetch

frontend/TestRun/PackagesInfo.svelte, frontend/TestRun/TestRun.svelte
This commit adds a new tab to SCT Test Run plugin - the Packages tab.
It displays all packages submitted during a test, such as scylla server,
upgraded version information and (in the future) tooling versions such
as python-driver, cassandra-stress and others.
Task: scylladb/qa-tasks#1543
=> feature(plugins/sct): Packages tab for SCT

argus/backend/service/stats.py
Reverts scylladb/argus#336
this code is breaking the release dashboards:
```
Feb 15 13:03:24 ip-10-0-2-112 bash[1100036]: [ERROR] <31.210.177.0 - https://argus.scylladb.com/api/v1/release/stats/v2?force=1&limited=0&productVersion=&release=enterprise-2024.1 - >
Feb 15 13:03:24 ip-10-0-2-112 bash[1100036]: Traceback (most recent call last):
Feb 15 13:03:24 ip-10-0-2-112 bash[1100036]:   File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_>
Feb 15 13:03:24 ip-10-0-2-112 bash[1100036]:     rv = self.dispatch_request()
Feb 15 13:03:24 ip-10-0-2-112 bash[1100036]:   File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispa>
Feb 15 …
```
=> Revert "fix(stats.py): Collect worst case comments and investigation"

argus/backend/controller/admin_api.py, argus/backend/controller/api.py, argus/backend/models/web.py, argus/backend/service/release_manager.py, argus/backend/service/stats.py, frontend/AdminPanel/ReleaseDeletionConfirmationPopup.svelte, frontend/AdminPanel/ReleaseEditor.svelte, frontend/AdminPanel/ReleaseManager.svelte, frontend/ReleaseDashboard/TestDashboard.svelte
This change allows administrators to define release's version regular
expression, which filters out versions displayed on the Release
Dashboard. For this purpose, a new menu was introduced in admin panel to
edit the release - setting the version regex makes the version bar on
the dashboard only display matching versions, for example: setting it to
"5.4(.*)" would only display versions starting with "5.4". This is
useful to filter out dev builds, erroneous submissions, missing versions
and rolling upgrades. Additionally, the behaviour of fetching "No
Version" runs was changed - a new checkbox was added to the dashboard
allowing user to set preference whether or not to fetch runs containing
no version alongside any versioned run. In case the checkbox is not
checked, there is a filter option …
=> feature(ReleaseDashboard.svelte): Improved version filtering

argus/backend/service/stats.py
Due to an issue in #336 there was a problem arranging information with
worst case if worst case was not one of the last 5 runs. This is now
fixed by slicing the array later and in case we are unable to find the
run still in the filtered out runs we reconstruct the required entity.
=> fix(stats.py): Fix worst-case collection

frontend/TestRun/DriverMatrixRunInfo.svelte, frontend/TestRun/Sirenada/SirenadaRunInfo.svelte, frontend/TestRun/TestRunInfo.svelte
This change adds a link to Jenkins rebuild page for each of the
supported TestRun cards. This is initial part of the logic to eventually
have automatic rebuilds/clones of Jenkins jobs inside argus.
Task: scylladb/qa-tasks#1612
=> improvement(TestRun.svelte): Rebuild link for Jenkins

frontend/Profile/Login.svelte, frontend/TestRun/DriverMatrixTestRun.svelte, frontend/TestRun/SCTSubTests/Gemini/GeminiTabComponent.svelte, frontend/TestRun/SCTSubTests/Performance/PerformanceTabComponent.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/TestRun/TestRun.svelte
This fixes an issue where repeated mount/dismount of component would
duplicate Font-Awesome icons in the markup, as they don't have same
cleanup procedures as svelte does.
Task: #341
=> fix(TestRun.svelte): Use svelte-fa instead of <i> tag

frontend/TestRun/DriverMatrixTestRun.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/TestRun/TestRun.svelte, frontend/WorkArea/TestRuns.svelte
This commit reverts the behaviour of TestRuns component where it will
now again refresh without tab being in focus
Fixes #343
=> fix(TestRuns.svelte): Re-enable background refresh for Workspace Runs

argus/backend/controller/testrun_api.py, argus/backend/service/jenkins_service.py, frontend/TestRun/DriverMatrixRunInfo.svelte, frontend/TestRun/Jenkins/BuildStartPlaceholder.svelte, frontend/TestRun/Jenkins/BuildSuccessPlaceholder.svelte, frontend/TestRun/Jenkins/CheckParam.svelte, frontend/TestRun/Jenkins/DummyCheckParam.svelte, frontend/TestRun/Jenkins/DummySelectParam.svelte, frontend/TestRun/Jenkins/JenkinsBuildModal.svelte, frontend/TestRun/Jenkins/ParamFetchPlaceholder.svelte, frontend/TestRun/Jenkins/ParameterEditor.svelte, frontend/TestRun/Jenkins/SCTParameterWizard.svelte, frontend/TestRun/Jenkins/SelectParam.svelte, frontend/TestRun/Jenkins/StringParam.svelte, frontend/TestRun/Jenkins/WizardUnavailable.svelte, frontend/TestRun/Sirenada/SirenadaRunInfo.svelte, frontend/TestRun/TestRunInfo.svelte
This PR replaces Jenkins rebuild URL with a custom wizard that
allows user to execute a job rebuild from inside Argus. The process is
split into two distinct phases - fetching and editing job parameters and
starting and verifying the job. On the first phase the user is presented
with a simple editor (currently only supporting string values) which
shows all parameters used for the job (with a toggle to show all
parameters for the entire workflow, i.e. empty ones), allowing user to
make necessary changes before starting rebuild. On the second phase the
job is started and verified until jenkins provides a build number and a
job url - at this point the wizard is finished and user is notified of
success.
Closes https://github.com/scylladb/qa-tasks/issues/1612
=> feature(argus): Job rebuild via Jenkins API 

argus/client/driver_matrix_tests/client.py, pyproject.toml
This commit adjusts which fields are required from a testcase, since
certain frameworks do not report classname in certain cases (e.g. rust
driver matrix)
=> fix(driver_matrix_tests): Make some fields optional in JUnit testcases

argus/backend/controller/testrun_api.py, argus/backend/service/jenkins_service.py, frontend/Common/JenkinsSettingsHelp.js, frontend/TestRun/DriverMatrixRunInfo.svelte, frontend/TestRun/Jenkins/Build.js, frontend/TestRun/Jenkins/BuildSuccessPlaceholder.svelte, frontend/TestRun/Jenkins/CloneCreatePlaceholder.svelte, frontend/TestRun/Jenkins/CloneTargetSelector.svelte, frontend/TestRun/Jenkins/JenkinsCloneModal.svelte, frontend/TestRun/Jenkins/LoadTargetsPlaceholder.svelte, frontend/TestRun/Sirenada/SirenadaRunInfo.svelte, frontend/TestRun/TestRunInfo.svelte
This commits adds logic and frontend components to clone a job inside
jenkins. The main difference between rebuild and clone being
the target release and group selector, in addition to "Advanced Settings"
menu, which differs between job types. All 3 main jobs types are
supported.
Task: scylladb/qa-tasks#1653
=> feature(jenkins_service): Job cloning for Jenkins

argus/backend/service/stats.py, frontend/ReleaseDashboard/ReleaseDashboard.svelte, frontend/ReleaseDashboard/TestDashboard.svelte, frontend/Stats/NumberStats.svelte, frontend/Stats/ReleaseStats.svelte
This commit changes text on investigation breakdown into buttons,
allowing quick selection of affected tests.
Fixes #72
Fixes #328
=> improvement(ReleaseDashboard.svelte): Quick filters for statuses

frontend/TestRun/ArtifactTab.svelte, frontend/TestRun/TestRun.svelte
This commit adds a form to the Logs tab of SCT TestRun component,
allowing user to submit a custom URL for a log (e.g. coredump url).
Task: scylladb/qa-tasks#330
=> feature(ArtifactTab.svelte): Add Log Link widget

argus/backend/service/argus_service.py, frontend/WorkArea/RunGroup.svelte, frontend/WorkArea/RunRelease.svelte
This commit fixes an issue where retrieving assignees for large releases
would not be possible due to exceeding max cartesian product defined for
IN queries. The queries are now split into 60 item batches (default
max cartesian product is 100 for scylla) to always be under this limit
and retrieve the schedules in batches, preventing issues like this from
occuring.
Fixes #350
=> fix(argus_service): Split assignee queries for large amount of groups

argus/backend/plugins/sct/service.py, argus/backend/plugins/sct/udt.py
This change ignores makes it so sct packages submitted to argus are
ignored if they match an already existing one.
=> improvement(plugins/sct): Ignore duplicate packages

argus/backend/plugins/sct/controller.py, argus/backend/plugins/sct/service.py, argus/backend/plugins/sct/types.py, argus/client/sct/client.py
This change adds a new endpoint for SCT controller that allows updating
almost all fields of a resource via a provided mapping (so that any
combination of valid fields is accepted server-side)
Task: scylladb/qa-tasks#1657
=> improvement(plugins/sct): Add update cloud resource endpoint

frontend/TestRun/ResourcesInfo.svelte
Changes duplicate "Provider" column header to "Region"
=> fix(ResourcesInfo.svelte): Incorrect column name

argus/backend/plugins/core.py, argus/backend/plugins/driver_matrix_tests/model.py, argus/backend/plugins/generic/model.py, argus/backend/plugins/sct/testrun.py, argus/backend/plugins/sirenada/model.py, argus/backend/service/stats.py, frontend/ReleaseDashboard/TestDashboard.svelte
This commit address performance bottlenecks in the stats fetching
module. Specifically it:
- No longer uses release_id index, instead opting out to an IN query
that includes relevant tests for the release
- The 15 test limit is now achieved via PER PARTITION LIMIT clause in
the stat query, instead of discarding indexed data
- To avoid exceeding maximum cartesian product of an IN query a
batching mechanism is introduced for reads, splitting stats query
into N amount of 100 test queries
- The queries themselves are using execute_async to execute in parallel
- Most linear searches are now replaced with map lookups (trading
multiple searches with an upfront map setup cost)
=> fix(stats.py): Refactor row-fetching for stats.

argus/backend/plugins/core.py, argus/backend/plugins/generic/model.py
This change fixes an issue where a submitted scylla version from generic
plugin would save it as is, leading to cluttering the short version
selector. The full version is still saved to a separate field for
additional filtering
=> fix(plugins/generic): Parse submitted scylla version

frontend/ReleaseDashboard/TestDashboard.svelte, frontend/ReleaseDashboard/TestPopoutSelector.svelte, frontend/Stats/NumberStats.svelte
This commit fixes and improves some of the usability issues related to
TestPopoutSelector.
* The button group now starts on top and follows cursor
* Double scroll has been removed
* A button to scroll to the top of the window has been added
* A "Remove All" button is now present alongside "Investigate Selected" button
* Quick filters are now explained better and contain additional buttons,
such as: Select all failed and not investigated, Select all
investigated without additional info.
* Version container has been adjusted slightly to contain its elements
better and also highlighted from the background
* The quick select buttons inside the investigation breakdown are now
indicated that are buttons better, using a chevron icon on each of
them.
* The build number on quick investigate …
=> improvement(ReleaseDashboard): UX adjustments for Quick Selector

argus/backend/service/jenkins_service.py
This fixes an issue where some jenkins jobs might not contain a display
name, leading to an error during clone.
Fixes #381
=> fix(jenkins_service.py): Skip changing display name if not present

argus/backend/models/web.py, argus/backend/service/testrun.py, frontend/Discussion/Comment.svelte, frontend/Profile/NotificationCommentWrapper.svelte, frontend/TestRun/TestRunComments.svelte
This commit adds functionality required to do replies inside
notification viewer, skipping the need for going into the main source
body and sending a comment there.
Fixes #203
=> feature(Notifications/Comment): Add inline reply to notifications

argus/backend/controller/testrun_api.py, argus/backend/service/testrun.py, frontend/Github/GithubIssue.svelte, frontend/Github/GithubIssues.svelte, frontend/WorkArea/TestRunsPanel.svelte, frontend/test-runs-breakout.js
This commit adds new button to the aggregated issue (an issue that
contains multiple runs, e.g. on release dashboard) that allows viewing
all the runs attached to it as a list. It also adds an endpoint to
resolve those runs into human readable strings to provide an overview.
Additionally, a new "Investigate selected" button is added on each modal
window to jump to workspace with **test** in question (each run is
clickable to get to the test+run page. Additionally, "Share" button on
workspace page is now fixed, Labels on issues are now individually
clickable (replicating "All labels" functionality) and the labels strip
is now hidden by default and is revealed by a button.
Fixes #157
=> improvement(GithubIssues.svelte): Modal window for viewing attached runs

argus/backend/controller/admin_api.py, argus/backend/service/release_manager.py, frontend/AdminPanel/ReleaseManager.svelte, frontend/AdminPanel/ReleaseManagerGroup.svelte, frontend/AdminPanel/ReleaseManagerTest.svelte
This commits adds quick switches to enable/disable groups and tests
inside admin management panel
Fixes #392
=> feature(AdminPanel): Quick toggles for Groups/Tests

argus/backend/service/build_system_monitor.py, argus_web.example.yaml, docs/dev-setup.md
This commit replaces exact substring match for release folder names with
a regex pattern search for releases, removing the need to manually add
release names into the scanner configuration. It also moves the scanner
configuration out of argus_web.yaml into module file itself, allowing
versioning of the scanner patterns.
Fixes #390
=> improvement(build_system_monitor): Use regex for folder scan

argus/backend/controller/api.py, argus/backend/service/argus_service.py, frontend/Common/ModalWindow.svelte, frontend/Common/SelectUtils.js, frontend/Profile/User.svelte, frontend/ReleasePlanner/ReleasePlanEditor.svelte, frontend/ReleasePlanner/ReleasePlanTable.svelte, frontend/ReleasePlanner/ReleaseScheduler.svelte
This commit reworks Release Planner wholesale, completely redoing the
way the table is structured. It is now similar in structure to the
TestDashboard used by Release Dashboard page and includes several new
features:
* Ability to select a whole group
* Collapseable groups that can be hidden when not needed
* Ability to batch edit a comment
* Ability to edit individual tests on a schedule
* Ability to reassign whole schedule to a different assignee
* Backlinks to the release dashboard
=> refactor(ReleaseScheduler.svelte): Release Assignee Planner rework

argus/backend/service/testrun.py
Fixes issues when deleting old schedules or schedules that are missing
plugins.
=> fix(service/testrun): Return nothing if re-assigning test with no plugin

argus/backend/plugins/core.py
This fixes an issue where a schedule contains either 0 or more than 1
assignee inside of a run. While we always expect only one assignee (and
only allow assigning one person), partial deletes of a schedule for any
reason might leave schedule without assignees and it could be retrieved
later.
Fixes #403
=> fix(plugins/core): use .extend instead of .append

frontend/TestRun/ResourcesInfo.svelte, frontend/TestRun/TestRun.svelte
Users need an easy way to clean resources left alive for given test id.
Added 2 buttons in resource tab:
1. By providing hydra clean-resources command to clipboard
2. By linking to jenkins cleanup job with parameters filled
Closes: https://github.com/scylladb/qa-tasks/issues/323
=> Cleanup test resources button

frontend/ReleasePlanner/ReleasePlanTable.svelte
This commit fixes sorting order for groups as previously they would be
sorted by only their internal name, and in cases where their display
name would be filled out this would cause confusion.
=> fix(ReleasePlanTable.svelte): Fix sorting order for groups

argus/backend/controller/client_api.py, argus/backend/controller/testrun_api.py, argus/backend/models/result.py, argus/backend/models/web.py, argus/backend/plugins/core.py, argus/backend/plugins/sct/testrun.py, argus/backend/service/client_service.py, argus/backend/service/testrun.py, argus/client/base.py, argus/client/generic_result.py, dev-db/docker-compose.yaml, docs/generic_results.md, frontend/TestRun/ResultsTab.svelte, frontend/TestRun/TestRun.svelte, pyproject.toml
Introduced generic results: allows clients to send arbitrary tabular
data to Argus and show it in `Results` tab in run view.
See [docs/generic_results.md](./docs/generic_results.md) for more details.
refs: https://github.com/scylladb/qa-tasks/issues/1244
=> feature(plugins/core): Generic Results

frontend/ReleaseDashboard/TestDashboard.svelte, frontend/ReleasePlanner/ReleasePlanTable.svelte
This change fixes an issue where dashboards would crash if a test was
added but stats would still be using previously cached values.
=> fix(frontend): Provide a placeholder status if stats are missing

frontend/ReleasePlanner/ReleasePlanTable.svelte
This fixes some issues where cached stats would miss a new test
=> fix(ReleasePlanTable.svelte): Handle missing tests and force no-cache

argus/backend/service/argus_service.py
This fixes an issue due to assignee id being the primary key which
causes CQL engine to treat the "old" entity as new one.
=> fix(argus_service.py): Delete previous assignee and create new one

argus/backend/service/build_system_monitor.py, argus/backend/service/views.py
This commit changes two instances of full scans currently used in Argus
to instead request unlimited amount of rows, rather than defaulting to
standard 10,000. This fixes issues where tests would be missing in
search queries or during build system scanner.
=> fix(argus/service): Remove implicit 10,000 entity limit on full scans

argus/backend/models/result.py, argus/backend/service/client_service.py
When test sends only one row to Argus it should be appended. So needs to update table metadata (only in case new row is added). In case of column/description changes, always update with new value.
Fixes issue when sending results in parts (row by row instead all at once)
=> fix(generic-result): fix updating table metadata

argus/backend/service/jenkins_service.py, argus/backend/service/user.py
argus rebuild is using the github id/login, to trigger job in jenkins while SCT uses by default the user from the primary email if it's part of scylla emails.
this small diffrence is cause confusion for users which thier email is diffrent from thier github login, and caused cloud resources to be forgotten
this change change the why we select the emails out of the github accout to default to scylla emails, and also to user the user from the email when rebuild jobs, so it would be aligned with SCT
=> fix(jenkins-triggering): pick the impersonate user according to email

argus/backend/plugins/sct/testrun.py, frontend/TestRun/IssueTemplate.svelte, frontend/TestRun/TestRunInfo.svelte
For jobs that run tests in parallel it's important to see what test method was used (e.g. in perf tests it defines the workload).
Added additional param that recently was added to SCT config (`test_method`) and it's displayed in "Run Details".
closes: https://github.com/scylladb/argus/issues/375
=> improvement(run details): added test method

argus/backend/service/testrun.py
This commit checks whether or not a queued mention would be for the user
writing the comment and prevent sending a notification for that mention.
Fixes #197
=> fix(service/testrun): Do not send a mention to yourself

frontend/Github/GithubIssues.svelte
This commit changes how copy to clipboard button works for Issue View,
allowing user to choose one of 3 formats (HTML, Markdown, Plain Text)
and showing him the selected issue table as Preview.
Fixes #388
=> feature(GithubIssues.svelte): Improved copy to clipboard UX

argus/backend/controller/client_api.py, argus/backend/service/client_service.py, argus/client/base.py
This commit adds a new endpoint and a client method to retrieve
currently instantiated run data. This is useful in case client wants to
check/validate run before doing something to it.
Task: scylladb/scylla-cluster-tests#7483
=> feature(argus/client): Endpoint for retrieving the run

argus/backend/util/config.py, dev-db/export_data.py, dev-db/import_data.py
Added possibility to download whole release data and import it without errors. Previous script didn't work if release/group/job was not imported previously.
=> improvement(test-data): download full releases data

frontend/WorkArea/RunGroup.svelte, frontend/WorkArea/RunRelease.svelte
This commit fixes an issue that might occur in cases where
`sanitizeSelector` function fails sanitize a selector made out of
concatenated release/group name, leading to a crash. The new method uses
UUID of the button object, i.e. either group id or release id,
preventing the issue from ever occuring.
=> fix(frontend/WorkArea): Use entity ids for sidebar buttons

argus/backend/plugins/core.py, argus/backend/plugins/driver_matrix_tests/controller.py, argus/backend/plugins/driver_matrix_tests/model.py, argus/backend/plugins/driver_matrix_tests/raw_types.py, argus/backend/plugins/driver_matrix_tests/service.py, argus/backend/plugins/driver_matrix_tests/udt.py, argus/client/driver_matrix_tests/cli.py, argus/client/driver_matrix_tests/client.py, frontend/Common/DriverMatrixTypes.ts, frontend/TestRun/DriverMatrixTestCollection.svelte, pyproject.toml
This commit reworks the way Driver Matrix Runs are submitted to Argus,
replacing previously one-shot architecture with a multi-stage pipeline
akin to SCT, where driver matrix run first submits itself, and then
submits results sequentially (either a pass or failure), finalizing with
a call that makes backend determine status based on resulting payload.
Patch failures are now supported. Entire logic was moved from the client
to the backend, removing the need to update the client in case of large
changes to the API / submitted data.
Fixes #289
=> refactor(plugins/driver_matrix_tests): Multi-stage pipeline for Drivers

frontend/TestRun/ResultsTab.svelte
When result table contains 0 value, it breaks because empty string is passed to `formatValue` function in this case.
This causes failure to conversion to string (and anyway is wrong).
=> fix(results-table): pass 0 value to formatValue instead string

argus/backend/controller/api.py, argus/backend/service/results_service.py, frontend/WorkArea/TestRuns.svelte, frontend/WorkArea/TestRunsSelector.svelte
In case graphs for given test are not available, showing graph button is misleading. This may cause people get used to missing graphs and never look there.
Fix is about showing graphs button only when there are results. Results are verified by metadata tables being present for given test.
=> fix(graphs): hide button if no graphs available

argus/backend/service/results_service.py, frontend/TestRun/ResultsTab.svelte
Sometimes results don't have units - in that case graphs and result tables print `[]` which is confusing.
Remove braces when no unit is present in graphs and result tables.
=> fix(results): remove units when not present

frontend/TestRun/ResultsGraph.svelte, frontend/TestRun/ResultsGraphs.svelte
Graph filters are adjusting according to selections - this behavior differs from one in results tables and confuses users. Also it's harder to switch between different graphs (as requires deselect previous filter to show the other ones).
Adjusted graphs filters to work similarly like in results tables. Graphs thou have another level of filtering: columns (as each table column is a separate graph). These filters are not exclusive and users can select multiple of them - to show interesting multiple columns only.
=> fix(graphs): adjust filters similar to result tables

frontend/TestRun/TestRunInfo.svelte
We want to show grafana link if monitor node is up, not only when test is in progress.
Still, because monitor state may be outdated, showing restore monitoring stack buttons.
There's a plan to improve keeping instances state up to date by enhancing cloud cleanup scripts to update Argus.
refs: https://github.com/scylladb/qa-tasks/issues/328
=> improvement(TestRunInfo): show grafana link if monitor is up

argus/backend/controller/api.py, argus/backend/controller/testrun_api.py, argus/backend/models/result.py, argus/backend/service/results_service.py, argus/backend/service/testrun.py, argus/client/generic_result.py, frontend/TestRun/Components/Cell.svelte, frontend/TestRun/Components/ScreenshotModal.svelte, frontend/TestRun/ResultsTab.svelte, frontend/TestRun/Screenshots.svelte, pyproject.toml
improvement(results): add sending text and screenshots
Implemented support for sending text results to argus.
Text results are ignored in graphs.
If a text result is a link to image it is shown as button which opens
given image in a modal (e.g. screenshots). This enables to send
screenshots from latency_decorator in SCT.
Also did a bit of refactor around results (moved fetching result tables
to `ResultsService` where fits better.
improvement(screenshots): move to separate component
Moved screenshot modal to separate component to reuse it.
Also added 'close by esc' feature.
=> improvement(results): add sending text and screenshots

argus/backend/service/client_service.py, argus/backend/service/notification_manager.py, argus/backend/service/testrun.py, frontend/Common/ArgusNotification.ts, frontend/Profile/Notification.svelte, frontend/Profile/NotificationTestRunWrapper.svelte, templates/notifications/assigned.html.j2, templates/notifications/assigned_email.html.j2
This commit adds both internal and email notification for assignments to
runs within argus. Manual assignments done by a user on a test run card
send a notification/email from him.
Fixes #398
=> improvement(notification_manager): Add "Assigned to a run" notification

argus/backend/service/testrun.py
This commit fixes an issue where assigning yourself to a run would send
a notification to the user.
Fixes #452
=> fix(service/testrun.py): Do not send a notification on self-assignment

frontend/TestRun/Jenkins/SCTParameterWizard.svelte
=> fix(SCTParameterWizard): Allow `-` (dash) as an RC separator

argus/backend/models/result.py, argus/backend/models/web.py, argus/backend/plugins/sct/testrun.py, argus/backend/service/client_service.py, argus/backend/service/results_service.py, argus/client/generic_result.py, docs/generic_results.md, pyproject.toml
Results to make difference need to change test status depending if are passing or failing. At first idea was to force clients to adjust test status. This commit adds possibility to Argus to track best results for given test and validate incoming results based on rules defined by Argus clients.
List of improvements:
1. Argus tracks best result for each column&row pair in tables, including `run_id` and `result_date` for future reference. Evaluated only when `higher_is_better` column metadata is set. Stored in separate table to track the changes (and correctly show validation rules calculated limits for given time)
2. Argus client may provide validation rules for each column. Supported validations (can set multiple of them):
- fixed_value - verifying if value is better than it
- best_pct - …
=> improvement(results): track best and validate results

frontend/TestRun/Components/Cell.svelte, frontend/TestRun/ResultsTab.svelte
Having screenshots in the table, copy table button does not copy it but just adds 'view' text.
Now this is fixed and copy table button copies link in markdown format for proper reference.
fixes: https://github.com/scylladb/argus/issues/450
=> fix(results): copy table copies screenshot links

argus/backend/models/result.py, argus/backend/service/results_service.py
In future we're going to need to fetch best results for given point in time. Currently it's not efficient as would require reading rows that happened after requested point in time. This is because 'result_date' where clause restriction must happen along with 'key' restriction.
To tackle that problem, need to reorder 'key' and 'result_date' columns. Better to do it early, before we have data there, so we don't need to migrate anything.
=> fix(results): fix ordering of best results table clustering keys

argus/backend/cli.py, argus/backend/models/result.py, argus/backend/service/results_service.py, argus/backend/tests/results_service/test_cell.py, argus/backend/tests/results_service/test_result_metadata.py, poetry.lock, pyproject.toml, pytest.ini
Ressurrecting unit-tests for backend. At first, introduced tests for generic results feature. Found few bugs and unneeded code along.
Tests are relying on containerized scylladb cluster (1 node) and reuse it for next tests runs for speed testing. Tests are designed in a way that can be run on the same db (without truncation). Although, there's an unused `truncate_all_tables` function in case it's needed (it adds few secs of overhead, so better not to use it).
refs: https://github.com/scylladb/argus/issues/468
=> improvement(tests): added unit tests for generic results

argus/backend/controller/main.py, frontend/TestRun/DriverMatrixTestRun.svelte, frontend/TestRun/Generic/GenericTestRun.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/TestRun/TestRun.svelte, frontend/run-by-plugin.js, templates/run_view_by_plugin.html.j2, webpack.config.js
This commit adds a new endpoint which replaces hard to use
/test/test_id/runs?additionalRuns[]=run_id endpoint into a much more
simpler /tests/plugin_name/run_id endpoint, allowing to build a link to
the test run without knowing test_id in advance and simplifying
sharing/searching for a run.
Part of Task: scylladb/qa-tasks#1490
=> improvement(frontend): Add frontend endpoint for plugin/run_id

frontend/TestRun/ResultsTab.svelte
When there's only 2 levels (groups) of filtering, filters are not shown. This is wrong assumption, e.g. In gradual throughput test when we have multiple result tables for each throughput with only latencies results.
Show filters when one filter level contains more than 1 filter.
=> fix(results): show filters when there are at least 2 in level

argus/backend/service/results_service.py, argus/backend/tests/results_service/test_best_results.py, argus/backend/tests/results_service/test_create_chartjs.py, frontend/TestRun/ResultsGraph.svelte
Added limit lines to graphs based on best results and validation rules. When creating graphs, for each point limit is calculated and plotted (also visible in the tooltip).
Have in mind that limits might differ from ones in "Results" tab as client might ignore rules (which most of our test cases currently do).
closes: https://github.com/scylladb/qa-tasks/issues/1763
=> improvement(results): add limit lines to graphs

argus/backend/service/results_service.py, argus/backend/tests/conftest.py, argus/backend/tests/results_service/test_best_results.py
Sometimes results might be wrong (e.g. wrong job configuration) leading to results that outstand and being irrelevant or updating best result value causing validation to break.
If job investigation status is set to `IGNORED` make Argus to skip plotting it and exclude from best results map.
closes: https://github.com/scylladb/argus/issues/462
=> improvement(results): exclude ignored results from graphs

argus/backend/controller/api.py, argus/backend/service/results_service.py, argus/backend/tests/results_service/test_chartjs_additional_functions.py, argus/backend/tests/results_service/test_create_chartjs.py, frontend/TestRun/Components/ScreenshotModal.svelte, frontend/TestRun/ResultsGraph.svelte, frontend/TestRun/ResultsGraphs.svelte
Performance job can run against different scylla release. Because it was
not taken into account, graph lines don't differentiate between them
making impossible to distinguish different releases.
This commit adds support for mixing different SUT releases in one job
and make them visible as separate series on graphs. Additional
'releases' filters were added to easily toggle releases that should be
shown.
closes: https://github.com/scylladb/argus/issues/473
=> Support multiple releases on graphs

argus/backend/error_handlers.py, argus/backend/service/client_service.py, argus/backend/tests/client_service/test_submit_results.py, argus/backend/tests/results_service/test_best_results.py, argus/backend/tests/results_service/test_validation_rules.py
In case there is a cell with 'ERROR' status, then respond with `error` status, so client may take proper action based on it (e.g. marking test as failed).
refs: https://github.com/scylladb/qa-tasks/issues/1765
=> improvement(results): respond with error when result failed

templates/base.html.j2
This commit fixes an issue where some users would not be able to use
argus because parts of their usernames contained unescaped json
sequences, which would fail JSON.parse. As a replacement, templates now
receive JSON as a JS object literal.
=> fix(templates/base.html.j2): Do not parse JSON provided by the backend

argus/backend/controller/api.py, argus/backend/service/results_service.py, argus/backend/tests/results_service/test_chartjs_additional_functions.py, argus/backend/tests/results_service/test_results_service.py, frontend/TestRun/ResultsGraphs.svelte
In order to narrow down graphs range, date filters were added (by start and end date) with ability to quickly switch between 1,3 and 6 recent months. Last 3 months filter is on by default.
closes: https://github.com/scylladb/argus/issues/474
=> feature(graphs): filter data points by date filters

frontend/TestRun/ResultsGraphs.svelte
Some improvements around graphs filtering: less colors, more organization and labels.
=> improvement(graphs-ux): graphs filters reorganization

argus/backend/service/planner_service.py, argus/backend/service/test_lookup.py, frontend/AdminPanel/ViewSelectItem.svelte, frontend/ReleasePlanner/ReleasePlannerGridView.svelte, frontend/ReleasePlanner/SearchBar.svelte, frontend/WorkArea/TestRuns.svelte, frontend/WorkArea/TestRunsPanel.svelte
This commit adds a global search bar to the Workspace page. This bar
allows user to search Argus for any test, group or release names, as
well as specific run ids. The following hapens for each:
* Test: a Test selector is added and shown to the user.
* Group: all Tests from a Group are added to the selector.
* Release: a Grid View is shown to the user to pick a single group or
test
* Test Run: a Test selector is added with a selected run automatically
opened
=> feature(WorkArea.svelte): Add global search to the Workspace

argus/backend/plugins/core.py, templates/releases.html.j2
This allows new planning to coexist with plans used in old ArgusSchedule
implementation.
=> fix(plugins/core): Add a fallback for old schedules

argus/backend/service/argus_service.py, argus/backend/service/stats.py
This commit fixes an issue where old schedules would not be counted for
tests that have not been run (but have been scheduled). This restores
both the assignee icon and NOT RUN status.
=> fix(stats.py): Add a fallback for old assignments and stats

argus/backend/service/stats.py
This fixes an issue where views would fail to fetch stats after rolling
back schedules for releases in #504.
=> fix(stats.py): Re-enable schedules for Views as well

frontend/AdminPanel/ViewsManager.svelte, frontend/Common/ViewTypes.js, frontend/Views/ViewDashboard.svelte, frontend/Views/Widgets/ViewUnsupportedPlaceholder.svelte
This fix addresses a potential issue where a widget created on a newer
version of argus will cause an error on an older one when it is loaded
from the database.
=> fix(ViewTypes.js): Add a fallback widget in case of undefined widgets

argus/backend/service/results_service.py, argus/backend/tests/results_service/test_chartjs_additional_functions.py, argus/backend/tests/results_service/test_create_chartjs.py, frontend/TestRun/ResultsGraph.svelte, frontend/TestRun/ResultsGraphs.svelte
In performance tests it's important to note changes of dependencies,
like kernel, drivers, stress tools and SUT version.
This commit changes the way point is displayed:
when there's package change (except SUT change) then the point gets
a white background.
Hovering over the point shows tooltip with all packages changes
(including SUT).
Tooltip position was adjusted to be show above the point so mouse is not
covering text.
closes: https://github.com/scylladb/argus/issues/490
=> improvement(graphs): Mark dependency changes

argus/backend/controller/view_api.py, argus/backend/controller/views_widgets/highlights.py, argus/backend/models/view_widgets.py, argus/backend/models/web.py, argus/backend/service/views_widgets/highlights.py, argus/backend/tests/conftest.py, argus/backend/tests/view_widgets/test_highlights_api.py, frontend/Common/AssigneeSelector.svelte, frontend/Common/ViewTypes.js, frontend/Discussion/UserProfile.svelte, frontend/Profile/UserSelection.svelte, frontend/ReleasePlanner/ReleasePlan.svelte, frontend/Views/WidgetSettingTypes/IntegerValue.svelte, frontend/Views/Widgets/ViewHighlights/ActionItem.svelte, frontend/Views/Widgets/ViewHighlights/Comment.svelte, frontend/Views/Widgets/ViewHighlights/HighlightItem.svelte, frontend/Views/Widgets/ViewHighlights/ViewHighlights.svelte, frontend/argus.css, poetry.lock, pyproject.toml
Introducing Highlights View Widget that should aid Views with important messages, action items and allow commenting upon them. Originally, intended for performance view dashboard, where important messages and action items are discussed over weekly performance regression tests.
With this widget, users may:
* create messages (highlights) for given view
* create action items and assign Assignee, mark item as done upon completion
* comment each highlight/action item
* archive hightlights/action items to hide it from the view
* unarchive it to bring it back
More info in ref issue.
refs: https://github.com/scylladb/argus/issues/485
=> improvement(views): Highlights View widget

argus/backend/service/stats.py
This commit fixes an issue where worst case collection function would
never take the branch to compare statuses, leading to last status always
being chosen - for 3 runs of (failed, pass, pass) the outcome would be
pass and for (failed, pass, failed) it would be failed. This commit
corrects this and now statuses are properly evaluated.
Fixes #488
=> fix(stats.py): Correctly collect worst-case status for tests

argus/backend/controller/main.py, frontend/Profile/ProfileJob.svelte
This commit adds error handling for two endpoints related to fetching
test runs. In case of ProfileJobs, it adds a message indicating to the
user that something went wrong, instead of showing loading forever.
The other case is specifying invalid id to the /tests/plugin endpoint,
in this case, a 404 redirect is generated with an error message.
Fixes #512
=> fix(frontend): Handle error conditions for retrieving test runs

frontend/ReleaseDashboard/TestDashboard.svelte
This commit adds a new button that will hide every NOT_PLANNED test on
the Test Dashboard. The setting is per-dashboard and is saved in the
user's local storage.
Fixes #429
=> improvement(TestDashboard.svelte): Add "Hide not planned" button

frontend/TestRun/Jenkins/BuildSuccessPlaceholder.svelte, frontend/TestRun/Jenkins/CloneSuccess.svelte, frontend/TestRun/Jenkins/JenkinsCloneModal.svelte, frontend/TestRun/TestRun.svelte, frontend/TestRun/TestRunInfo.svelte, frontend/WorkArea/TestRunDispatcher.svelte, frontend/WorkArea/TestRuns.svelte, frontend/WorkArea/TestRunsPanel.svelte
This commit adds a new button alongside "Configure" button on the job
collapse, allowing user to clone a job without having to run one first.
In this case, the parameter retrieval is skipped initially, and the
parameters are retrieved from the new job. In case of pressing this
button on a job with runs, the flow is largely the same as normal clone,
the parameters are taken from the latest job. Additionally, for
usability, last stage now gives user possibility to instantly add newly
created job to the workspace.
Fixes #379
=> feature(frontend): Add possibility to clone empty jobs

argus/backend/plugins/driver_matrix_tests/model.py, argus/backend/plugins/generic/model.py, argus/backend/plugins/sct/testrun.py, argus/backend/plugins/sirenada/model.py
This commit fixes an issue where generic runs would fail to submit due
to not finding a test entity associated with a run when storing a
version. It adds exception handling to submit_product_version on every
plugin to fix that.
Fixes #524
=> fix(plugins/core): Handle missing tests in get_assignment calls

argus/backend/controller/view_api.py, argus/backend/controller/views_widgets/summary.py, argus/backend/service/results_service.py, argus/backend/tests/results_service/test_results_service.py, argus/backend/tests/results_service/test_validation_rules.py, frontend/Common/ViewTypes.js, frontend/Github/GithubIssues.svelte, frontend/Github/GithubIssuesCopyModal.svelte, frontend/TestRun/Components/ResultTable.svelte, frontend/TestRun/ResultsTab.svelte, frontend/Views/Widgets/SummaryWidget/RunIssues.svelte, frontend/Views/Widgets/SummaryWidget/SummaryWidget.svelte
View widged showing tests statuses and results per Scylla version. Each test can be expanded to see results (tables) with key metrics. Initial features:
1. Results summary by scylla version (date, scm revision)
2. passed tests are collapsed by default
3. not run tests marked as warning
4. hiding tables with all cells green ... many more but small ones.
caveats:
1. works only with scylla-server package
2. tests filtering based on release (oss vs enterprise) implementation is poor as will work only with scylla-master and scylla-enterprise argus releases
3. key metrics are hardcoded, followup issue: https://github.com/scylladb/qa-tasks/issues/1821
Did a refactor of ResultsTab - extracted ResultTable to be able to reuse it across different parts of Argus (like Summary Widget)
refs: …
=> feature(summary-widget): summary widget

argus/backend/service/results_service.py
We want to easily diffirentiate between releases and point styles are not good for it. Use different colors for releases and various dashes patterns for rows (cycles).
deployed on staging.
dashed lines for cycles:
=> improvement(graphs): use colors for releases

argus/backend/service/results_service.py
Before implementing proper fix with ability to SUT package for graphs, introducing quick issue workaround to enable work with some tests.
refs: https://github.com/scylladb/argus/issues/550
=> fix(graphs): automatic SUT issue workaround

argus/backend/plugins/sct/testrun.py
=> fix(sct/testrun): Check for duplicate entries on log submit

frontend/Views/Widgets/SummaryWidget/SummaryWidget.svelte
When scrolling Scylla versions in summary widget, tests are appearing in random order. Sort it by test name.
=> fix(summary-widget): sort tests

frontend/Discussion/CommentEditor.svelte, frontend/Views/Widgets/ViewHighlights/ActionItem.svelte, frontend/Views/Widgets/ViewHighlights/HighlightItem.svelte, frontend/Views/Widgets/ViewHighlights/ViewHighlights.svelte
Added support for highlights widget.
Reused 'comments' editor known from job discussions. Thus implementing all that is supported by this component: titles, links, multi-line content, code blocks etc.
One caveat: mentioning does not trigger notifications yet. This is going to be done in followup task.
closes: https://github.com/scylladb/argus/issues/510
=> improvement(highlights): add markdown support

argus/backend/controller/views_widgets/highlights.py, argus/backend/models/web.py, argus/backend/service/notification_manager.py, argus/backend/service/views_widgets/highlights.py, argus/backend/tests/view_widgets/test_highlights_api.py, frontend/Common/ArgusNotification.ts, frontend/Profile/Notification.svelte, templates/notifications/view_action_item_assigned.html.j2, templates/notifications/view_action_item_assigned_email.html.j2
When assigning action item in Highlights Widget,
assignee will get Argus Notification with
link to the view and action details.
closes: https://github.com/scylladb/argus/issues/500
=> improvement(highlights): send notification to action item assignee

frontend/Views/Widgets/ViewHighlights/ActionItem.svelte
Action items missed one div enclosing mark. Fix it to repair layout.
=> fix(hightlights-view): fix comment section in action items

argus/backend/controller/main.py
This commit provides a graceful error message when supplied UUID for a
test is invalid for /tests/$plugin/$uuid endpoint.
Fixes #527
=> fix(controller/main.py): Validate UUID before trying to retrieve it

start_argus.sh
Per https://uwsgi-docs.readthedocs.io/en/latest/FallbackConfig.html this
disables uWSGI "no app loaded" mode to prevent issues such as #534 from
occuring
Fixes #534
=> fix(start_argus.sh): Disable uwsgi dynamic app mode

argus/backend/plugins/sct/controller.py, argus/backend/plugins/sct/service.py, argus/client/sct/client.py
This commit adds logic to add SCT runner to the resource table and also
adds client support for its name. Additionally, it adds a workaround for
older client versions, where SCT runner will be submitted without a
name.
Fixes scylladb/scylla-cluster-tests#9543
=> fix(plugins/sct): Support SCT runner for resources table

argus/backend/plugins/core.py, argus/backend/service/argus_service.py, argus/backend/service/stats.py, templates/releases.html.j2
This commit enables new release planner for all releases within argus
and deprecates previously available timed "Duty Planning" feature. It
removes most checks for 'perpetual' release flag when retrieving
assignes and allows plans to be read for those releases as well, as well
as enabling the button to open the planner for such releases.
=> improvement(feature/planner): Enable for all releases

frontend/Views/Widgets/ViewHighlights/ViewHighlights.svelte
Highlights widget gets redrawn when userList changes. This is not required usually as userList should not change.
fixes: https://github.com/scylladb/argus/issues/564
=> fix(highlights): don't redraw on usersList update

argus/backend/controller/api.py, argus/backend/service/results_service.py, frontend/Common/ModalWindow.svelte, frontend/TestRun/Components/GraphFilters.svelte, frontend/TestRun/Components/ResultTable.svelte, frontend/TestRun/Components/ScreenshotModal.svelte, frontend/TestRun/ResultsGraph.svelte, frontend/TestRun/ResultsGraphs.svelte, frontend/TestRun/ResultsTab.svelte, frontend/Views/Widgets/SummaryWidget/SummaryWidget.svelte
When viewing results tables users now can view graph for selected column to see values from the past/future.
closes: https://github.com/scylladb/qa-tasks/issues/1822
after clicking one:
clicking on the point opens new browser window (popup, without navigation bar) with selected test run.
Works also in summary view widget.
=> improvement(graphs): add show graph button for each column in results

frontend/TestRun/IssueTemplate.svelte, frontend/TestRun/ResourcesInfo.svelte, frontend/TestRun/StructuredEvent.svelte, frontend/TestRun/TestRunInfo.svelte
This commit adds success indicators when user does copy-to-clipboard
actions, making it less confusing.
Fixes #431
=> improvement(TestRunInfo.svelte): Add popup hints for copy buttons

argus/backend/error_handlers.py
This commit adds additional information and trace ids to the exception
that occur inside the API calls, allowing to collect more information
about the error, including the request data.
Fixes #492
=> improvement(error_handlers): Add context dump to the exceptions

frontend/TestRun/ResultsGraph.svelte
Graph tooltips now can be clicked to make it stick - eases screenshot, enables copying content. Also has clear button ("open") for opening related test. Tests are open in new popup window, so user doesn't lose focus from graph and can open multiple windows with tests.
closes: https://github.com/scylladb/argus/issues/508
=> improvement(graph): sticky tooltips

argus/backend/controller/planner_api.py, argus/backend/models/plan.py, argus/backend/models/web.py, argus/backend/service/jenkins_service.py, argus/backend/service/planner_service.py, argus/client/generic/cli.py, argus/client/generic/client.py, docs/api_usage.md
This commit adds a new feature to the Release Planning API - allowing
API consumers to trigger jobs from within argus in Jenkins. The endpoint
accepts target version (for example "6.2.0") in which case it will
trigger all plans with this version (release independent), release name
(will trigger all plans within that relase) or specific plan id (will
only trigger that plan). The API client provides the parameters in two
parts: as a set of common parameters intended for each job (useful for
things like provision_type) and an additional per job
type/backend/region set that each job will require in order to trigger.
Currently, only longevity is supported.
Fixes #377
=> feature(service/planner_service): Trigger jenkins jobs by plans

argus/backend/service/results_service.py, frontend/TestRun/ResultsGraph.svelte, frontend/TestRun/ResultsGraphs.svelte
Graphs got subtitle based on result table's description.
closes: https://github.com/scylladb/argus/issues/496
example:
=> improvement(graphs): add subtitle from table description

argus/backend/controller/api.py, argus/backend/models/result.py, argus/backend/models/web.py, argus/backend/service/results_service.py, argus/backend/tests/results_service/test_results_service.py, frontend/TestRun/Components/Filters.svelte, frontend/TestRun/ResultsGraphs.svelte
Users are allowed to create 'Graph Views' which can store specific
graphs. Created Graph Views are visible in test's graph window and can
be selected for quick look on saved graphs list. This way saving time
for playing with filters.
Graph Views may have a name and description.
closes: https://github.com/scylladb/argus/issues/554
Main View with all the graphs:
When View is activated:
Adding new view:
Graphs may be added/removed by left top corner button (with tooltip).
Filters are created for each Graph View and work within it.
=> feature(graphs-views): show predefined list of graphs

docs/argus_status_page.md
Deploying status page lambdas require to log in to AWS as `DevOpsAccessRole`. Added note about it.
=> fix(docs): status page lambda deploy

frontend/TestRun/EventsTab.svelte, frontend/TestRun/StructuredEvent.svelte
Some events happen during multiple nemeses. This commit updates the
logic to find all nemeses that were active during a specific event,
instead of just looking for one like previously.
Fixes #470
=> improvement(EventsTab): Multi-nemesis events

frontend/TestRun/Components/ResultTable.svelte
fixed few issues in copy markdown support for results tables.
fixes: https://github.com/scylladb/argus/issues/577
=> fix(results): fix copy markdown button

dev-db/export_data.py, dev-db/import_data.py
Import/export scripts missed graphs data which is needed for debugging localy issues on prod. Added support for graphs data.
=> improvement(db-scripts): improve import/export scripts

frontend/TestRun/Components/ResultTable.svelte
There were assumption, than columns without unit are textual and don't have graphs. This is wrong - perf simple query results don't have units but have graphs.
Fix is about using proper assumption: if column type is not TEXT then there is graph.
=> fix(results): fix show graph for columns without unit

argus/backend/plugins/sct/udt.py
The default value of state field was not being serialized properly due
to cqlengine being unable to handle Enum classes, fixed by getting the
Enum value in the default handler. This fixes an issue where SCT runner
would not be set with a vague "SyntaxException" error due to not
providing ResourceState.
=> fix(plugins/sct): Fix serialization of ResourceState enum

argus/backend/plugins/driver_matrix_tests/model.py
This commit changes the way driver results are interpreted on argus
side. Instead of trying to guesstimate the overall status of the test
the status received from pipeline is now used.
=> fix(plugin/driver_matrix_tests): Use status from pipeline

argus/backend/models/result.py, argus/backend/service/results_service.py, argus/backend/tests/client_service/test_submit_results.py, argus/backend/tests/results_service/test_result_metadata.py, argus/client/generic_result.py
In some cases it will be hard to automatically select proper SUT - test that runs for the first time, or not supported package name by automatic sut selection.
Allowed client (tests) to specify 'sut_package_name' - bypassing automatic selection.
fixes: https://github.com/scylladb/argus/issues/550
=> improvement(results): allow manual sut selection

frontend/Views/Widgets/ViewHighlights/ActionItem.svelte, frontend/Views/Widgets/ViewHighlights/HighlightItem.svelte
Missed `markdown-body` class for highlights widget making tables not displayed correctly.
=> fix(highlight): fix markdown formatting

frontend/argus.js
This temporary fix (until #531 is done) will force markdown to be always
rendered in light mode, preventing issues when users have their browser
theme set to Dark.
Fixes #598
=> fix(frontend/argus.css): Force lightmode for markdown comments

argus/backend/controller/view_api.py, argus/backend/controller/views_widgets/nemesis_stats.py, argus/backend/service/views_widgets/nemesis_stats.py, frontend/Common/ViewTypes.js, frontend/Views/Widgets/ViewNemesisStats.svelte
We want to see nemesis statistics run for selected release. Something similar we currently have in elasticsearch. In this initial version user gets 2 charts:
1. Pie chart showing statistics of overall nemesis pass/failure rate
2. Bar chart with corresponding nemesis pass/failure rates
additionally, stats for number of hours nemesis run and distinct nemesis executed.
All data can be filtered per release/specific patch version.
refs: https://github.com/scylladb/argus/issues/446
[from staging](https://argus.scylladb.com/view/scylla-2025-1-2025-1-0-test-plan):
=> improvement(view_widget): new nemesis stats widget

argus/backend/plugins/sct/service.py, argus/backend/plugins/sct/testrun.py
This commit adds additional logic to package/version submission APIs,
changing the way scylla_version field is set on an SCTTestRun (which
gets later used by TestDashboard widget to filter runs by version).
Primarily, the change is here to address rolling-upgrade runs being
hidden by version filters inside said dashboard when they fail without
upgrading to target version. Because of this, the logic now does the
following:
* A new field has been added to SCTTestRun class, named 'version_source'
* Said field is used to restrict certain APIs from further changing
the version based on certain conditions
* submit_product_version will now not set the version if version_source
has any content (we ignore updates to it from SCT when it installs
scylla)
* submit_packages will now check if a package …
=> improvement(plugins/sct): Use 'target' packages to set version

frontend/Common/ViewTypes.js
This fixes missing ReleaseStats widget
=> fix(ViewTypes.js): Rename duplicate key

argus/backend/service/stats.py
Fixes an issue where the filter would return keys of a single plan
instead of potential plans for view.
=> fix(stats.py): Split filter expression

argus/backend/controller/main.py, frontend/ReleasePlanner/ReleasePlan.svelte, frontend/ReleasePlanner/ReleasePlanner.svelte, frontend/Views/ViewDashboard.svelte, frontend/plan.js, webpack.config.js
This commit adds two-way linking between a plan and a view. In addition,
plans now have a separate route, allowing them to be opened standalone
from planner (Editing features not available).
Fixes #611
=> feature(ReleasePlanner): Backlinks between plan and view

frontend/ReleasePlanner/ReleasePlannerGridView.svelte
This fix fixes an issue where GridView would crash if a release was set
to dormant (so stat fetches don't happen) as well as it forces the stat
fetch to occur even if release is dormant.
=> fix(ReleasePlannerGridView): Null-check group stats and force fetch

frontend/ReleasePlanner/ReleasePlanCreator.svelte
This commit makes it so that if a user was assigned to a group before
expansion that user is copied to all tests that will be added to the
plan.
Fixes #612
=> improvement(ReleasePlanCreator): Copy assigned user into expanded group

argus/client/base.py, argus/client/driver_matrix_tests/cli.py, argus/client/driver_matrix_tests/client.py, argus/client/generic/cli.py, argus/client/generic/client.py, argus/client/sct/client.py, argus/client/sirenada/client.py, pyproject.toml
for purpose of identificaton of the code part sending out results into argus, we should be able to configure as needed the headers the client are sending out.
this change introducs extra argument to clients, and to thier CLIs
=> Add option to pass on extra headers into Argus clients

argus/backend/plugins/sct/service.py
while trying to submit results into Argus from SCT, I've run into those failures that cause in turn to Argus not have the scylla version
```
Traceback (most recent call last):
File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.12/lib/python3.12/site-packages/flask/app.py", line 880, in full_di>
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/argus/.cache/pypoetry/virtualenvs/argus-alm-HqUqk8xE-py3.12/lib/python3.12/site-packages/flask/app.py", line 865, in dispatc>
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/argus/app/argus/backend/service/user.py", line 261, in wrapped_view
return view(*args, **kwargs) …
```
=> fix `submit_packages` API to not fail on empty `version_source`

poetry.lock, pyproject.toml
Because of restriction enforced in pyproject.toml it is not possible to install argus client in 3.10 envirionments.
Loosen that restriction and updated packages.
fixes: https://github.com/scylladb/argus/issues/619
=> fix(installation): allowed using python 3.10 and updated packages

argus/client/driver_matrix_tests/cli.py
in the finish-run command the `extra_headers` argumnet was missing while it was define as click option, and when it would be passed to the function it would fail
this introduce the argument, and pass it to the ArgusClient
=> fix(driver_matrix_test.cli): add missing extra_headers arguments

argus/backend/service/jenkins_service.py, frontend/TestRun/Jenkins/BuildConfirmationDialog.svelte, frontend/TestRun/Jenkins/JenkinsBuildModal.svelte, frontend/TestRun/Jenkins/JenkinsCloneModal.svelte, frontend/WorkArea/TestRuns.svelte
This commits adds a new button to the test runs within argus, allowing
user to either start a build from scratch or rebuild a latest run
without having to open a run to do so. The from scratch implementation
will try to retrieve previous build parameters (In case previous build
wasn't submitted to argus) and if that's not possible, will offer user
to start a build without parameters to be able to retrieve the build on
subsequent call.
Fixes #542
=> improvement(WorkArea): Add Test Execute button

argus/backend/service/views_widgets/nemesis_stats.py, frontend/Views/Widgets/ViewNemesisStats.svelte
When viewing nemesis stats, user might want to drill down to failures to see more details.
Added possibility to click on nemesis bar (on the graph) to show tabular data about failed/passed runs - similar like it was in ES. User may go to specific test run or just view stack traces of nemesis failures.
closes: https://github.com/scylladb/argus/issues/626
deployed to staging: https://argus-staging.lab.dbaas.scyop.net/view/scylla-2025-1-2025-1-0-test-plan
=> feature(nemesis_widget): allow drill down to test runs

frontend/TestRun/jUnitResults.svelte
Excludes child nodes `system-out` and `system-err` when looking for nodes useful for deducing test status. Currently if `system-out` is present for passing test it will in the end be classified as "Disabled".
=> Add exclusions to parsejUnitXml in jUnitResults

frontend/TestRun/ResultsGraph.svelte, frontend/TestRun/ResultsGraphs.svelte
Open run button in tooltip was a button and was opening linked run in popup window. This is not what users expect.
Changed it to be normal link - so user sees where it links on hover and may use right click to select how to open it. By default it opens in new tab.
=> improvement(graphs): graph run link in tooltip opens new tab

frontend/TestRun/DriverMatrixTestRun.svelte, frontend/TestRun/Generic/GenericTestRun.svelte, frontend/TestRun/Sirenada/SirenadaTestRun.svelte, frontend/TestRun/TestRun.svelte
After recent changes, tab content is recreated when swiching tabs. This causes error of comment content disappear and also reloads events each time events tab is visited (etc.).
This fix makes behavior like before, so tab content is not recreated after visiting it.
fixes: https://github.com/scylladb/argus/issues/641
=> fix(testRun): fix disappearing comment content

frontend/Views/Widgets/SummaryWidget/SummaryWidget.svelte
We used to mix tests for enterprise/OSS versions in a view. When selecting one of it we wanted to exclude tests from the other (seeing only enterprise tests when enterprise version were selected). 
Now it's no longer needed and we started to mix master and enterprise tests in one view causing tests from `scylla-master` release not appearing.
fix by removing this filter.
=> fix(summaryWidget): remove filtering tests based on product

.github/workflows/release.yml
This action works on Workflow dispatch (i.e. manually triggered) and will push the release into Pypi and create GH release and tag with autogenerated release notes
=> feature(ci): Automate Release process

argus/backend/plugins/core.py, argus/backend/plugins/sct/testrun.py, argus/backend/service/client_service.py
since for `scylla-server` we can have multiple names availble in diffrent stages of the test we should honor those name, so if we report thing before the some of them are reported, it should still work.
regardless the default behavier of `sut_timestamp` should follow the `sut_package_name` if provided, it make much more sane usability-wise.
=> fix(sut_timestamp): lookup all the possible package names

poetry.lock, pyproject.toml
* dev-dependencies are deprecated since poetry 1.2
* poetry.lock was regenerated with `poetry update`
=> improvement(poetry): Use dev group

.github/workflows/lint.yml, .github/workflows/test.yml
- Small improvement, should lower CI times (they are low regardless)
- To make sure cache can be reused, use the same dependencies in all actions 
- Do not freeze poetry version in CI
=> improvement(ci): Use cache for dependencies

argus/backend/controller/planner_api.py, argus/backend/service/planner_service.py, argus/backend/service/views.py, frontend/AdminPanel/ViewsManager.svelte, frontend/ReleasePlanner/ReleasePlanCreator.svelte, frontend/ReleasePlanner/ReleasePlanner.svelte, frontend/Views/ViewSelect.svelte
This commit adds additional logic to support attaching an existing view
to a newly created (or one being edited) plan. Attached view will
preserve its name and description, as well as widgets, but its selection
will be replaced by plan's selection. Additionally, when deleting a
plan, a new checkbox has been added to prevent attached view from being
deleted (in this case it just detaches and becomes a free-standing
view). To handle corner cases, Admin users can now also edit the plan_id
field of views inside view manager, in case manual intervention is
required.
For views, it is assumed that they only linked to 1 plan and cannot be
relinked from a plan without being detached first. The detachment can be
done in two ways:
* Create a new view and attach it to a plan, thereby detaching the …
=> improvement(release_planner): Allow user to attach an existing view

argus/backend/service/planner_service.py, argus/backend/tests/client_service/test_submit_results.py, argus/backend/tests/results_service/test_best_results.py, argus/backend/tests/results_service/test_validation_rules.py, argus/client/generic_result.py, argus/client/tests/test_results.py, pyproject.toml
Currently, `GenericResultTable` is highly tied to the Meta class, which contains validation logic for validation rule. This creates a necessity of using Meta class even for cases where name is dynamic, which results in nested classes like this:
```python
def send_perf_simple_query_result_to_argus(argus_client: ArgusClient, result: dict):
stats = result["stats"]
workload = result["test_properties"]["type"]
parameters = result["parameters"]
class PerfSimpleQueryResult(GenericResultTable):
class Meta:
name = f"{workload} - Perf Simple Query"
description = json.dumps(parameters)
Columns = [ColumnMetadata(name="allocs_per_op", unit="", type=ResultType.FLOAT, higher_is_better=False),
ColumnMetadata(name="cpu_cycles_per_op", unit="", type=ResultType.FLOAT, higher_is_better=False), …
```
=> improvement(client): Allow GenericResultTable with dynamic parameters

frontend/TestRun/Jenkins/ParameterEditor.svelte, frontend/TestRun/Jenkins/TextParam.svelte
Allow some parameters that are multiline in Jenkins to be multiline in Argus, so editing them is easier without having to add newline chars manually.
closes: #668
=> feature(TestRun/Jenkins): allow some parameters to be multiline

pytest-argus-reporter/pytest_argus_reporter.py, pytest-argus-reporter/tests/conftest.py, pytest-argus-reporter/tests/test_argus_reporter.py
this field was missing and been send over via `user-fields` by mistake
=> fix(pytest-reporter): enable sending the message on it's own

README.md
Badge was working, but the link was not added.
=> fix(readme): Add missing link to pypi to badge

argus/backend/controller/views_widgets/graphed_stats.py, argus/backend/service/views_widgets/graphed_stats.py, frontend/Common/TestStatus.js, frontend/Github/GithubIssue.svelte, frontend/TestRun/StructuredEvent.svelte, frontend/Views/Widgets/ViewGraphedStats.svelte, frontend/Views/Widgets/ViewGraphedStats/AssigneeCell.svelte, frontend/Views/Widgets/ViewGraphedStats/Interfaces.ts, frontend/Views/Widgets/ViewGraphedStats/InvestigationStatusCell.svelte, frontend/Views/Widgets/ViewGraphedStats/IssuesCell.svelte, frontend/Views/Widgets/ViewGraphedStats/NemesisTable.svelte, frontend/Views/Widgets/ViewGraphedStats/PaginatedTable.svelte, frontend/Views/Widgets/ViewGraphedStats/StatusBadge.svelte, frontend/Views/Widgets/ViewGraphedStats/StatusCell.svelte, frontend/Views/Widgets/ViewGraphedStats/TestRunTable.svelte, frontend/argus.css
- Add new backend endpoint `/widgets/runs_details` for fetching detailed test run information
- Implement batched data fetching for issue links, GitHub issues, and test run metadata
- Enhance TestRunTable component with user avatars, hover tooltips, and assignee display
- Add support for all test status types (FAILED, TEST-ERROR, PASSED, ABORTED, RUNNING) with appropriate colors
- Implement GitHub issue badges with open/closed state styling
- Add investigation status indicators as colored circles with hover text
- Include column header tooltips for better UX when names are truncated
- Update type definitions for enhanced test run data structure
Backend changes:
- New GraphedStatsService.get_runs_details() method with error handling
Frontend changes:
- Enhanced TestRunTable with async data …
=> feat(graphed-stats): enhance test run details with assignees, issue

argus/backend/service/results_service.py
Sometimes value sent to results might be 0. This was evaluated to false and considering a cell to be text one.
Fix by verifying if value is not `None`.
fixes: https://github.com/scylladb/argus/issues/687
=> fix(results): don't return null for 0 values

argus/backend/controller/view_api.py, argus/backend/service/planner_service.py, argus/backend/service/stats.py, frontend/AdminPanel/ViewWidget.svelte, frontend/AdminPanel/ViewsManager.svelte, frontend/Common/ViewTypes.js, frontend/ReleaseDashboard/FlatViewHelper.svelte, frontend/ReleaseDashboard/GroupedViewHelper.svelte, frontend/ReleaseDashboard/TestDashboard.svelte, frontend/ReleaseDashboard/TestDashboardFlatView.svelte, frontend/ReleaseDashboard/TestDashboardGroup.svelte, frontend/ReleaseDashboard/TestDashboardTest.svelte, frontend/ReleasePlanner/ReleasePlan.svelte, frontend/Views/ViewDashboard.svelte, frontend/Views/Widgets/ViewTestDashboard.svelte
This commit implements per-widget entitity filtering for views,
allowing users to select which tests/groups/releases they want shown on
the widget in a specific view. To facilitate this, stat fetching has
been modified to accept widget id (position) of a view and then filter
tests accordingly. On the frontend side to facilitate conflict-free stat
fetching (for example from two TestDashboards) a hashmap has been
introduced to handle multiple stat objects and to dispatch them
correctly to each widget.
Caveats:
* Release Planner views in general are not supported and contain
several unwanted interactions:
* If test dashboard is modified to filter anything, release
planner stat bar will be gray (since there's no more anchor
for it to get the stats from)
* Anything version related will …
=> improvement(ViewDashboard): Per-widget item filtering

frontend/TestRun/TestRunInfo.svelte
Test methods name can be long, overflowing into other half of the table and overshadowing text there
Example:
https://argus.scylladb.com/tests/scylla-cluster-tests/6624c84b-65a9-4086-8286-312911feeb69
=> improvement(TestRunInfo): Add text-break to Test method

MANIFEST.in
this is used to exclude files from the `argus-alm` package it was forgotten and wasn't committed during the work on switching to uv
=> Introduce `MANIFEST.in`

argus/client/generic_result.py, argus/client/tests/test_results.py
This makes it on par with GenericResultTable in terms of init parameters
=> fix(generic_result): Add missing init params to StaticGenericResultTable

argus/backend/service/results_service.py
Because fetch run info was limited to 10, we could see only several recent scylla versions in summary widget.
I don't remember why we needed that. Probably it was just overlooked thing.
fixes: https://github.com/scylladb/argus/issues/701
=> fix(summary_widget): fix limited version

frontend/TestRun/ResultsTab.svelte
- Updated `.result-list` container to allow horizontal scrolling when ResultTable components are too wide.
- Ensures all table content remains accessible regardless of width.
fixes: https://github.com/scylladb/argus/issues/689
=> fix: Add horizontal scrolling to result tables in ResultsTab

argus/backend/service/results_service.py
- Filter out None values in get_min_max_y() before sorting to prevent TypeError
- Add None check in coerce_values_to_axis_boundaries() before value comparisons
- Return default (0, 0) bounds when no valid numeric data points exist
- Prevents crashes when chart datasets contain null/None values
fixes: https://github.com/scylladb/argus/issues/711
=> fix: handle None values in chart data processing

frontend/Views/Widgets/SummaryWidget/SummaryWidget.svelte
In summary view widget test status was either failed, passed or other so user needed to go into the test to see actual status (and sometimes it was aborted or running etc.).
Show different icons for each test status so user quickly get's idea what's the actual status without getting into test run details.
fixes: https://github.com/scylladb/argus/issues/709
=> improvement(summary_widget): distinguish test statuses

argus/backend/models/argus_ai.py, argus/backend/plugins/sct/service.py, argusAI/event_similarity_processor.py, argusAI/pyproject.toml, argusAI/uv.lock, frontend/TestRun/EventsTab.svelte, frontend/TestRun/StructuredEvent.svelte
When user looks at events tab, often there are duplicates, blurring the image and it's harder to spot distinct events.
Fix by using similar events engine to detect duplicates within the same run and hide them from user (with ability to show).
How it works:
1. similar event engine detects duplicate events in the same run
2. save them along with similar events (new `duplicates_list` column)
3. Argus UI fetches duplicates along with similar list
4. Argus constructs 'distinct_events' (ones that are not duplicates - meaning being a first occurence of this event) and next events that are duplicates of it, are appended to a list of duplicates
5. When user clicks 'Show duplicates', duplicates of selected event are shown with light blue background color
6. User may then hide duplicates by clicking …
=> feature(similar_events): hide duplicates

frontend/TestRun/EventsTab.svelte
- Ensure distinctEvents and shownDuplicates are initialized for all severities (ERROR, CRITICAL, WARNING, NORMAL, DEBUG)
- Add null checks and simplify display logic to avoid accessing undefined properties
- Now WARNING, NORMAL, and DEBUG events are always shown when enabled, regardless of similar_events response
- Prevents "Cannot read properties of undefined (reading 'hasOwnProperty')" error
fixes: https://github.com/scylladb/argus/issues/731
=> Fix: prevent crash when similar_events is empty on Events tab

frontend/Github/GithubIssues.svelte
Fixes an issue where sorting by title and repo would lead to nonsensical
ordering.
Fixes #727
=> fix(GithubIssues.svelte): Fix comparison function for strings

argus/backend/controller/view_api.py, argus/backend/controller/views_widgets/pytest.py, argus/backend/models/pytest.py, argus/backend/models/web.py, argus/backend/service/client_service.py, argus/backend/service/testrun.py, argus/backend/service/views_widgets/pytest.py, argus/backend/tests/conftest.py, argus/backend/tests/pytest_service/test_submit_results.py, argus/backend/util/encoders.py, frontend/Common/TestStatus.js, frontend/Common/ViewTypes.js, frontend/Views/Widgets/PytestWidget/PytestCalendarSelector.svelte, frontend/Views/Widgets/PytestWidget/PytestCollapseHelper.svelte, frontend/Views/Widgets/PytestWidget/PytestFlatHelper.svelte, frontend/Views/Widgets/PytestWidget/PytestOverviewWidget.svelte, frontend/Views/Widgets/PytestWidget/PytestResultRow.svelte, frontend/Views/Widgets/PytestWidget/PytestTableWidget.svelte, frontend/Views/Widgets/PytestWidget/ViewPytestOverview.svelte, scripts/migration/migration_2025-07-18.py
This commit adds a new View Widget, intended to provide overview into
specific test's pytest results, such as statistics, charts and a
searchable result list. The new widget supports both views and release
pages, supporting both always open and collapsed options.
Widget features:
* Filter tests by cut off date or by range of dates
* Filter by test status
* Filter by test marker
* Filter by test user specified field presence
* Filter by text within the test
Fixes scylladb/qa-tasks#273
=> feature(frontend): Pytest Overview Widget

frontend/TestRun/Pytest/PytestItem.svelte, frontend/TestRun/Pytest/PytestRun.svelte, frontend/TestRun/Pytest/types.ts
This commit brings some refactoring towards PytestRun items.
* Default filters have been changed to only show bad statuses.
* Added focus check to not refresh data when tab is not in focus
* Reworked the accordion stack into rows similar to overview widget with
some fields rearranged
* Added lazy fetch for user fields
* Fixed status colors
Fixes #728
=> improvement(PytestRun.svelte): Pytest View improvements 

argus/backend/controller/api.py, argus/backend/controller/view_api.py, argus/backend/plugins/core.py, argus/backend/plugins/sct/testrun.py, argus/backend/service/argus_service.py, argus/backend/service/stats.py, argus/backend/service/views.py, argus/backend/util/common.py, frontend/Common/TestStatus.js, frontend/ReleaseDashboard/AssigneeFilter.svelte, frontend/ReleaseDashboard/TestDashboard.svelte, frontend/ReleaseDashboard/TestDashboardFlatView.svelte, frontend/ReleaseDashboard/TestDashboardGroup.svelte, frontend/ReleaseDashboard/TestDashboardTest.svelte
This commit adds new filtering options to the TestDashboard component.
To simplify adding additional filters, a filtering stack object was
introduced to define a filtering operation, its state and its comparison
operation. Each filter state is saved into local storage upon
interaction and restored when reloading the page. Previously available
filters were reworked for the new system.
The filters are:
* Assignee
* Status (Improved) - Can now filter out any status, not just not planned
* Backend (New) - Filters to SCT tests using specified backend
* ImageId (New) - Filters to SCT tests using specified image
Fixes #319
=> improvement(TestDashboard): Extended filters

frontend/Github/GithubIssue.svelte, frontend/Github/GithubIssues.svelte, frontend/TestRun/IssueTab.svelte
This commit adds a feature which allows user to quickly attach an
existing issue shown in "All issues for this test" tab into the current
run.
Fixes #708
=> feature(IssueTab.svelte): Add quick issue link to aggregated issue view

argus/backend/service/stats.py
This commit changes behaviour of the scylla version filter within
TestDashboard widget. Previously, scyllaVersion query param would result
in a strict a == b comparison, which could exclude runs from appearing
in the filtered dashboard. This also allows us to fold long versions
based on regex rule to match both short version strings and long version
strings.
Fixes #752
=> improvement(stats.py): Relax version filter to match from the start

frontend/Views/ViewDashboard.svelte, frontend/view-dashboard.js
This commit fixes an issue where productVersion query parameter would be
ignored, but also incorrectly assigned to the widget version filter.
Fixes #751
=> fix(ViewDashboard.svelte): Correctly assign and get productVersion

argus/backend/plugins/generic/model.py
Since promote-release job reports versions with a dash instead of a
tilde, this causes short version to become just "rc1", which is not very
helpful. This commit adds dash as a valid character for short version.
=> fix(generic/model.py): Properly handle promote-release version

frontend/TestRun/Components/ResultTable.svelte
Fixes an issue where a single markdown table couldn't be copied.
Fixes #777
=> fix(ResultTable.svelte): Resolve promise for individual tables

frontend/TestRun/Jenkins/SCTParameterWizard.svelte
Jenkins pipeline allows searching for AMIs using scylla build tag,
this commit adds this to the SCTParameterWizard.
Fixes #775
=> fix(SCTParameterWizard): Add fuzzy ami re searching

frontend/Common/SelectUtils.js
This commit adds normalization and removal of diacritic characters from
usernames that contain them, simplyfying filtering for them
Fixes #617
=> fix(SelectUtils): Add normalization for non-latin names

argus/backend/plugins/sct/controller.py, argus/backend/plugins/sct/plugin.py, argus/backend/plugins/sct/service.py, argus/backend/plugins/sct/testrun.py, argus/backend/tests/conftest.py, argus/backend/tests/sct_events/test_sct_events.py, argus/client/sct/client.py, argus/common/sct_types.py
This commit reworks the way SCT Events are stored by argus, by adding
several endpoints to store and get events separately from the usual
SCTTestRun entity, allowing quicker lookups, indexing and better
structure for events themselves. Previously, events were strings stored
on a collection of objects (severity, events), this commit replaces that
with a new table called SCTEvent.
Current endpoints:
* submit
* Supports both single and multiple event submits
* get
* Supports per partition limit to return limited amount of events
per severity
Tests are included in argus/backend/tests/sct_events/
Fixes #786
=> feature(plugins/sct): SCT Events Rework

argus/backend/plugins/sct/testrun.py, argus/backend/service/stats.py, frontend/ReleaseDashboard/TestDashboardTest.svelte
This commit adds extra information to test blocks on a TestDashboard,
namely:
* The amount of passed/failed nemesis is now reflected for SCT runs
* The time taken is displayed under the test
Fixes #597
=> improvement(TestDashboardTest): Add triage information to test

argus/backend/service/argus_service.py
This fixes an issue where a planned job for user might not be fully
initialized, leading to being unable to find a corresponding plugin for
the test.
Fixes #792
=> fix(argus_service): Do not try to look for jobs if no plugin is set

argus/backend/error_handlers.py, argus/backend/metrics.py, argus_backend.py, pyproject.toml, start_argus.sh, uv.lock, uwsgi.ini
This commit adds new metrics functionality to be collected by prometheus for
tracking application status. Currently tracks all requests and
exceptions and provides them on /metrics endpoint (requires auth on
prod)
=> feature(app): Prometheus Application Metrics

argus/backend/plugins/core.py
There's been an error `TypeError: can't compare offset-naive and offset-aware datetimes` after changing all to timezone aware.
=> fix(subimt_run): fix submit run with legacy schedule

argus/backend/controller/auth.py, argus_web.example.yaml, frontend/Profile/Login.svelte
Full repo access is not required anymore and checkbox to disable it is not needed.
closes: https://github.com/scylladb/argus/issues/797
=> fix(login): remove full repo access
