argus/db/cloud_types.py
argus/db/testrun.py

[Trello](https://trello.com/c/RKXXpoKk/4142-fix-argus-saving-logs-using-k8s-backends)

fix(argus.db.testrun): Remove backend check from ResourceSetup factory

---

argus/db/testrun.py

fix(argus.db.testrun): Demote info log messages to debug

---

argus/backend/api.py
argus/backend/argus_service.py

This commit adds version endpoint available at /api/v1/version
[Trello](https://trello.com/c/3B0LOisZ/4391-add-version-endpoint)

feature(argus.backend.api): Add version endpoint

---

argus/backend/assets/TestRun/TestRun.svelte

[Trello](https://trello.com/c/N8Yxnju9/4393-show-build-number-from-the-left-side-near-the-run-status)

fix(argus.frontend/TestRun.svelte): Show build number link on the left

---

argus/backend/assets/TestRun/TestRunInfo.svelte

[Trello](https://trello.com/c/dIthA0bO/4495-make-all-the-keys-names-in-details-bold)

fix(TestRunInfo.svelte): Use keys as list markers

---

argus/backend/assets/Common/DateUtils.js
argus/backend/assets/TestRun/ResourcesInfo.svelte
argus/backend/assets/TestRun/TestRun.svelte
argus/backend/assets/TestRun/TestRunInfo.svelte
argus/backend/assets/WorkArea/Test.svelte
argus/backend/assets/WorkArea/TestRuns.svelte
package.json
yarn.lock

Adds a utility function timestampToISODate, which pretty-formats
timestamps in various sections to provide better readability of said
timestamps
[Trello](https://trello.com/c/XvDGONKK/4491-improve-timestamps-readability)
Must be merged after #16

improvement(argus/frontend): More readable timestamps

---

argus/backend/assets/TestRun/TestRunInfo.svelte

[Trello](https://trello.com/c/fWzjIj8B/4493-move-test-run-details-button-group-to-the-bottom-of-the-box)

improvement(TestRunInfo.svelte): Move the button group to the bottom

---

argus/backend/assets/Common/UserUtils.js
argus/backend/assets/Profile/User.svelte
argus/backend/assets/TestRun/TestRun.svelte

Show full name, icon and a header line in an assignee box on test run
page
[Trello](https://trello.com/c/3LF2eFJC/4545-add-assignee-text-label-for-the-test-run)

improvement(TestRun.svelte): Show full name, icon and a header line

---

argus/backend/assets/Common/RunUtils.js
argus/backend/assets/TestRun/IssueTemplate.svelte
argus/backend/assets/TestRun/TestRunInfo.svelte

This commit adds kernel version tracking to both TestRunInfo and
IssueTemplate svelte components.
[Trello](https://trello.com/c/Xi2q8IXm/4583-add-kernel-info-to-the-test-run-info)

feature(TestRunInfo.svelte): Kernel Version Tracking

---

argus/backend/assets/TestRun/IssueTemplate.svelte
argus/backend/assets/TestRun/ResourcesInfo.svelte
argus/backend/assets/TestRun/TestRun.svelte

This commit reworks resources from the card format into a table format.
It also removes resources accordion and replaces it with a single table
that allows sorting and filtering, much like nemesis table.
[Trello](https://trello.com/c/0vXaAVpe/4576-resources-tab-v2)

feature(ResourcesInfo.svelte): Resource Tab rework

---

argus/backend/assets/Profile/User.svelte
argus/backend/assets/Stats/ReleaseStats.svelte
argus/backend/assets/Stats/TestMapStats.svelte
argus/backend/assets/Stores/AssigneeSubscriber.js
argus/backend/assets/TestRun/TestRun.svelte

This PR adds a mechanism which will display current assignee for this
week on each test run, provided it wasn't overriden by individual run
assignee
[Trello](https://trello.com/c/nXWmGj2S/4544-auto-assign-person-to-the-test-runs-according-to-the-duty-plan)

feature(argus.frontend): Automatic assignment of test runs

---

argus/backend/assets/TestRun/IssueTemplate.svelte

[Trello](https://trello.com/c/hKNKiY8X/4736-fix-issue-template-no-resources-left-at-the-end-of-the-run)

fix(IssueTemplate.svelte): Always show db nodes

---

argus/backend/api.py
argus/backend/argus_service.py
argus/backend/assets/ReleasePlanner/CommentTableRow.svelte
argus/backend/assets/ReleasePlanner/ReleasePlanTable.svelte
argus/db/models.py

This adds a new column to the release planner titled "Comment", allowing
user to add and edit a comment on each test available in the release
planner.
[Trello](https://trello.com/c/O3lGHBzp/4765-ability-to-comment-on-specific-job-in-release-duty-plan)
https://user-images.githubusercontent.com/7761415/158654708-28f1261b-fc65-4fb8-b1be-19c973b676ed.mp4

feature(ReleasePlanner.svelte): Comment column

---

argus/backend/api.py
argus/backend/argus_service.py
argus/backend/assets/Github/GithubIssue.svelte
argus/backend/assets/Github/GithubIssues.svelte
argus/backend/event_processors.py
argus/db/models.py

This commit adds a button onto the Issue component which allows
(after a confirmation) a removal of an issue attached to a run.
Closes #47 
[Trello](https://trello.com/c/cVUryW9H/4824-remove-an-issue-link-attached-to-the-test-run)
Demo:
https://user-images.githubusercontent.com/7761415/159164346-8f50bd0b-58f3-4e1a-b1a4-747e42b9721f.mp4

feature(GithubIssue.svelte): Ability to remove an issue from a run

---

argus/backend/api.py
argus/backend/argus_service.py
argus/backend/assets/ReleasePlanner/DutyPlanner.svelte
argus/backend/assets/ReleasePlanner/ReleasePlanTable.svelte
argus/backend/assets/ReleasePlanner/ReleaseScheduler.svelte
argus/backend/assets/ReleasePlanner/Schedule.svelte
argus/backend/assets/ReleasePlanner/ScheduleTable.svelte
argus/backend/assets/Stats/TestMapStats.svelte

This commit adds a reassignment feature to existing schedules and adds a
confirmation window to delete schedule button.
[Trello](https://trello.com/c/2vbkVh8J/4812-support-re-assign-person-in-the-release-plan)

feature(Schedule.svelte): Delete confirmation and reassignment

---

argus/backend/assets/TestRun/TestRun.svelte

This commit removes a behaviour where TestRun component would try to
place a placeholder assignee when the run doesn't have one, but the
schedule does.
[Trello](https://trello.com/c/AGesbDKi/4852-if-person-unassigned-it-should-not-show-the-current-group)

fix(TestRun.svelte): Do not auto-fill assignee field from schedule

---

argus/backend/__init__.py
argus/backend/api.py
argus/backend/argus_service.py
argus/backend/assets/Discussion/Comment.svelte
argus/backend/assets/Discussion/CommentEditor.svelte
argus/backend/assets/Discussion/MentionSelector.svelte
argus/backend/assets/Discussion/UserProfile.svelte
argus/backend/assets/Profile/User.svelte
argus/backend/assets/TestRun/TestRun.svelte
argus/backend/assets/TestRun/TestRunComments.svelte
argus/backend/assets/argus.css
argus/backend/assets/argus.js
argus/backend/assets/markdownOptions.js
argus/backend/templates/base.html.j2
argus/db/models.py
package.json
yarn.lock

This commit adds a new comment experience, which adds a new editor which
supports preview, common markdown actions and better text editing
handling. It also adds an ability to edit submitted comments and to
delete them. Additionally, it lays the groundwork for mention and
reaction system.
[Trello](https://trello.com/c/cHoGwwEL/4673-discussions-tab-v2)
Demo:
https://user-images.githubusercontent.com/7761415/160470899-6e772c3c-a3ad-4f4a-9d16-8a8e4cfcffcb.mp4

feature(argus.frontend): Discussions Tab v2

---

argus/backend/templates/base.html.j2

Fixes an issue where there would be an exception trying to read a
non-existent property if a user is logged out.

fix(base.html.j2): Check if user is logged in

---

argus/backend/assets/TestRun/TestRunComments.svelte

This prevents an issue where editor would reset every time there was a
comment fetch.

fix(TestRunComments.svelte): Do not hide editor on comment fetch

---

argus/backend/argus_service.py
argus/backend/event_processors.py
argus/db/models.py

This adds events for comment editing and deletion and creates them on
such actions
[Trello](https://trello.com/c/cHoGwwEL/4673-discussions-tab-v2)

improvement(argus_service.py): Events for Comment edits and deletions

---

argus/backend/assets/Github/GithubIssue.svelte
argus/backend/assets/Github/GithubIssues.svelte

[Trello](https://trello.com/c/93EfmQCx/4896-release-dashboard-all-issues-add-date-when-issue-added)

improvement(GithubIssue.svelte): Show date & order issues by date

---

argus/backend/controller/api.py
argus/backend/service/argus_service.py
frontend/Profile/ProfileSchedules.svelte

[Trello](https://trello.com/c/e1Ip3qmt/4963-show-comment-in-my-schedule)

improvement(ProfileSchedules.svelte): Show planner comment on a test

---

argus/backend/db.py
argus/backend/logsetup.py
argus/db/interface.py
argus_backend.py

This adds basic logging setup with a custom formatter that outputs
request information. It also configures loggers for argus,
werkzeug, uwsgi and cassandra modules
[Trello](https://trello.com/c/oo5bpjB1/4954-setup-logger)

improvement(argus): Setup custom logging formatter and module logs

---

argus/backend/service/argus_service.py

[Trello](https://trello.com/c/fR1OQygA/4973-collect-stats-and-release-dashboard-shows-disabled-tests)

fix(argus_service.py): Do not collect stats for disabled tests

---

argus/backend/build_system_monitor.py
argus/backend/controller/api.py
argus/backend/service/argus_service.py
argus/backend/service/release_manager.py
argus/db/models.py
frontend/AdminPanel/GroupCreator.svelte
frontend/AdminPanel/ReleaseManagerGroup.svelte
frontend/ReleasePlanner/ReleasePlanTable.svelte
frontend/WorkArea/RunGroup.svelte
poetry.lock
pyproject.toml

This PR adds support for recursive build_system_monitor scan,
additionally providing small fixes around the system for sanitizing
group selectors, empty stats for a group and admin panel having build_id
and enabled checkbox in release manager module
[Trello](https://trello.com/c/3oD4ibQt/4977-make-build-system-monitor-recursive)

feature(argus.build_system_monitor): Recursive build_system_monitor

---

argus/backend/controller/admin_api.py
argus/backend/controller/api.py
argus/backend/service/argus_service.py
argus/backend/service/release_manager.py
frontend/AdminPanel/ReleaseManager.svelte
frontend/AdminPanel/ReleaseManagerGroup.svelte
frontend/AdminPanel/ReleaseManagerTest.svelte
frontend/ReleasePlanner/Schedule.svelte
frontend/Stats/TestMapStats.svelte
frontend/WorkArea/Test.svelte

This PR contains multiple fixes regarding admin dashboard and things that can stem from administrator adjusting things in the dashboard - hidden/deleted tests, groups. It also includes a small adjustment to the release dashboard - Failed and not investigated runs will now show a border around them to indicate urgency:

Admin dashboard fixes

---

poetry.lock
pyproject.toml

make sure dependencies are open enough

---

argus/backend/service/argus_service.py
frontend/Stats/TestMapStats.svelte

[Trello](https://trello.com/c/qQigW7tJ/4986-sort-by-pretty-name-in-release-dashboard)

fix(TestMapStats.svelte): Order groups on release dashboard by name

---

.dockerignore
Dockerfile
argus/db/config.py
argus_backend.py
docker-entrypoint.sh
docker/config/nginx-docker.conf
docker/config/supervisord.conf
poetry.lock
pyproject.toml

This PR adds necessary configuration and scripts to automatically build a docker image. Currently, it's an image that includes both nginx (with its own configuration) and argus uwsgi app. Both are controlled by supervisord daemon, which is the entrypoint to the docker image.
[Trello](https://trello.com/c/B2tD7C7y/4675-dockerize-argus-web-app)

feature(argus): Dockerfile and docker image support

---

docker/config/nginx-docker.conf
docs/config/argus.nginx.conf
uwsgi.ini

This commits configures uwsgi properly for production usage, namely:
GIL is enabled, master process is being used, application is loaded into
each worker (instead of sharing memory), using unix socket instead of
tcp socket, using single interpreter mode and addition of stats socket

improvement(uwsgi): uWSGI configuration improvements

---

.eslintrc.js
.prettierrc.js
package.json
yarn.lock

This commit adds ESLint for linting and enforcing a code style and
Prettier code formatter for formatting files. It also adds matching
configurations to them.

improvement(argus): Add linter and formatter for JavaScript

---

argus/backend/service/argus_service.py
templates/notifications/mention.html.j2

[Trello](https://trello.com/c/Az1zGsU6/5120-notifications-use-old-testrun-route)

fix(NotificationManager): use main.runs route for run links

---

README.md

docs(README.md): Add database setup instructions

---

frontend/TestRun/NemesisReason.svelte
frontend/TestRun/NemesisTable.svelte

fix(NemesisTable.svelte): Remove preceding whitespace from stack trace

---

frontend/Discussion/Comment.svelte
frontend/TestRun/TestRunComments.svelte

This commit adds a "Quote Reply" button to the Comment component,
allowing user to quote a specific comment when creating a new comment
Closes #124

feature(TestRunComments.svelte): Quoting when submitting new comment

---

argus/backend/service/stats.py

This commit changes behaviour of the stats collector. Previously, run
status would be collected from latest run based on the timestamp value.
Now, the last 10 runs are sorted according to their build number and a
special status map is generated that contains "worst" status for that
build number - in case there are multiple runs with the same build
number, as that would be the case in rolling upgrade runs, for example.
[Trello](https://trello.com/c/URRW4N5U/5322-collecting-stats-for-upgrade-jobs)

improvement(service/stats.py): Calculate status based on build_number

---

argus/backend/plugins/core.py
argus/backend/plugins/sct/resource_setup.py
argus/backend/plugins/sct/service.py
argus/backend/plugins/sct/testrun.py
argus/backend/plugins/sct/udt.py
argus/client/__init__.py
argus/client/base.py
argus/client/sct/client.py
argus/client/sct/types.py

This PR adds a REST API client for Argus, as both a generic base
client and an SCT client.
Closes scylladb/qa-tasks#431
[Trello](https://trello.com/c/djMstpPv/5338-argus-rest-api-api-client)

feature(argus): REST HTTP Client

---

argus/backend/service/argus_service.py
argus/backend/service/notification_manager.py
argus/backend/util/send_email.py
argus_web.example.yaml
scripts/download_runs_from_prod.py
scripts/fix_run_metadata.py
templates/notifications/email_mention.html.j2

Trello: https://trello.com/c/IX07Qglw
If user will be mentioned in comments, the email notification
will be sent to mentioned user.

feature(email_notification):Send email notification

---

argus/backend/service/notification_manager.py
argus/backend/util/send_email.py

Add to constructor parameter which allow to create connection
one time during initializtion or each time befor send
fix issue #168

fix(send_email): Init smtp connection for each send or for all

---

.github/workflows/main.yml
frontend/Common/RunUtils.js
frontend/TestRun/IssueTemplate.svelte
frontend/TestRun/TestRunInfo.svelte

* add those to web run info
* add those to issue template
Ref: https://github.com/scylladb/scylla-cluster-tests/pull/5512

Add scylla-operator package/version information

---

frontend/TestRun/TestRunInfo.svelte

* remove the oprator version out of upgradeVersion if

Fix version indentation to be more clear

---

frontend/Profile/JobsList.svelte

This adds pagination and splits "My Jobs" runs into groups of 10 each, improving usability when having a lot of jobs on that page

improvement(JobsList.svelte): Pagination support

---

argus/backend/service/release_manager.py
frontend/AdminPanel/ReleaseManagerTest.svelte
frontend/AdminPanel/TestCreator.svelte

This adds an ability for the admin user to adjust the plugin used for the specific test inside Release Manager Admin Panel

improvement(ReleaseManager): Allow selecting plugin for a test

---

frontend/TestRun/IssueTemplate.svelte

* Moved issue description on top of the template
* Added Impact field
* Added Frequency field
* Added checkmark to describe if this is a regression or not
* Added collapse for logs and commands
Task scylladb/qa-tasks#926

improvement(IssueTemplate.svelte): Reorganize and improve issue template

---

frontend/ReleaseDashboard/TestDashboard.svelte

This commit adds a client-side collapse to the groups of tests and a mechanism to persist user preferred collapse state across sessions via local storage.
Task: scylladb/qa-tasks#939
Demo:

improvement(TestDashboard.svelte): Add a client-saved collapse to groups

---

argus/client/driver_matrix_tests/client.py

This fixes KeyError issues resulting from xUnit xmls missing attributes

fix(driver_matrix_tests.client): Better handling of testcase attributes

---

argus/backend/service/argus_service.py

This improvement allows release manager to quickly unassign people from tests related to a schedule. Due to current architecture we cannot do such task in the background and thus this operation might be expensive if the schedule in question contains a LOT of runs.
Task: scylladb/qa-tasks#941

improvement(argus_service.py): Unassign runs from deleted schedules

---

argus/backend/service/testrun.py

The database might contain test run records which may be missing their
test_id, release_id and group_id fields, either due to not having the
Test entity created for it in the first place or being deleted later,
this is now handled by first trying to recover the fields by re-running
assign_categories method of PluginModelBase and an exception handler is
added to log subsequent failure.

fix(service.testrun): Try to recover and handle missing test_id field

---

frontend/TestRun/EventsTab.svelte
frontend/TestRun/StructuredEvent.svelte

This changeset is aimed to improve usability of the new Events Tab
- Added a button to copy the whole raw event
- The event message box now displays whole raw event
- Severity filter buttons are now easier to press
- Added nemesis-related fields to DisruptionEvent
- Adjusted the color scheme for severities
- Re-added the event counts to the severity filter buttons
- The event period type button is now displayed for every event period
- Added icons to clickable areas

improvement(EventsTab.svelte): Usability improvements

---

frontend/TestRun/EventsTab.svelte
frontend/TestRun/StructuredEvent.svelte

show which nemesis ran during each event
on events tab

improvement(events tab): show nemesis that happened

---

argus/backend/plugins/sirenada/model.py
argus/backend/plugins/sirenada/plugin.py
argus/backend/plugins/sirenada/types.py
argus/client/sirenada/client.py
frontend/Common/PluginDispatch.js
frontend/TestRun/Sirenada/SirenadaRunInfo.svelte
frontend/TestRun/Sirenada/SirenadaTestRun.svelte
pyproject.toml

This commit adds required backend changes and a client for 
submitting sirenada results. It also adds a (very) basic
test run card for viewing the results.
Task: scylladb/qa-tasks#826

Argus Sirenada Support

---

argus/backend/controller/client_api.py
argus/backend/service/client_service.py
argus/client/base.py

Extend Argus client to get testrun status.

feature(API): get testrun status

---

argus/backend/plugins/sct/controller.py
argus/backend/plugins/sct/service.py
argus/backend/plugins/sct/testrun.py
argus/client/sct/client.py
frontend/TestRun/TestRunInfo.svelte
pyproject.toml

This commit addresses a problem where due to Argus runs now being
submitted much earlier in SCT pipeline, an SCT runner might not be exist
yet - leading to most information about it being useless. This commit
introduces a separate endpoint to submit SCT Runner information and
removes code that would extract this information on the initial
submission

fix(plugins/sct): Add separate sct runner submission endpoint

---

argus/backend/plugins/sct/testrun.py
frontend/TestRun/IssueTemplate.svelte
frontend/TestRun/TestRunInfo.svelte

This change adjust the requirement to have sct_config dict during run
submission to allow later submission, and the method from_sct_config now
supports updating the record in addition to creating the run record.

improvement(plugins/sct): Make SCT Config dict optional on submission

---

argus/client/driver_matrix_tests/client.py

added gocql driver matrix support

feature: add gocql driver matrix support

---

frontend/Common/IssueDestinations.js
frontend/Common/PluginNames.js
frontend/Github/GithubIssues.svelte
frontend/TestRun/IssueTab.svelte
frontend/TestRun/Sirenada/SirenadaIssueTemplate.svelte
frontend/TestRun/Sirenada/SirenadaTestRun.svelte

Add the ability to open issues to "siren", "siren-frontend" and "siren-devops"
fixes https://github.com/scylladb/argus/issues/267

fix(sirenada): Add the ability to open issues to "siren", "siren-frontend" and "siren-devops"

---

frontend/ReleaseDashboard/TestDashboard.svelte

This change adds a button to collapse or expand groups on test
dashboard. The collapse button shows when there are any groups to
collapse and expand all button shows when all groups are collapsed.
Fixes #318

improvement(TestDashboard.svelte): Add Collapse/Expand all buttons

---

argus/backend/plugins/sct/service.py
argus/backend/util/enums.py
frontend/Common/TestStatus.js
frontend/Common/TextUtils.js
frontend/ReleaseDashboard/TestDashboard.svelte
frontend/TestRun/RunStatusButton.svelte
frontend/argus.css

This commit adds one new failure status (to be set manually for now) -
TEST-ERROR. The old FAILED status is now considered a
run failure, while the new one allows tracking framework or
infrastructure issues (e.g. spot instance not available)
or when the job fails due to testing framework bug.
Fixes #316

feature(argus): New Failure Status

---

argus/backend/service/stats.py

This change adjusts the behaviour of stats collector to always show last
status to be the worst case for the grouped runs - runs such as rolling
upgrades will now display comments and investigation status for the
worst case out of all of them.
Fixes #317

fix(stats.py): Collect worst case comments and investigation

---

argus/backend/plugins/sct/udt.py
argus/client/sct/client.py
frontend/TestRun/ResourcesInfo.svelte

This change allows Argus to track datacenter names inside
CloudInstanceDetails.
Fixes #222

improvement(plugins/sct): Store DC Name in CloudInstanceDetails

---

argus/backend/plugins/sct/service.py

This change makes argus look for CoreDumpEvent events in submitted
events on test completion - parsing ones that contain links to coredumps
and storing them in the 'logs' container, which can be viewed on the
"Logs" tab in the frontend. Note that some cores might be lost if SCT
generates a lot of error events, shadowing last 100 it submits to argus.
Fixes #326

improvement(plugins/sct): Scan for CoreDumpEvent on events submission

---

argus/backend/plugins/loader.py
argus/backend/plugins/sct/controller.py
argus/backend/plugins/sct/plugin.py
argus/backend/plugins/sct/service.py
argus/backend/plugins/sct/testrun.py
argus/client/sct/client.py
frontend/TestRun/TestRun.svelte
frontend/TestRun/jUnitChart.svelte
frontend/TestRun/jUnitResults.svelte
pyproject.toml

This change allows SCT clients to submit JUnit xml to argus and let it
be parsed into a user-viewable table on the SCT run component widget.
Fixes #345

feature(plugins/sct): JUnit results table and submission support

---

argus/backend/controller/testrun_api.py
frontend/WorkArea/JobConfigureModal.svelte
frontend/WorkArea/TestRuns.svelte
frontend/argus.css

This commit adds Jenkins settings page to the TestRuns banner (while
also slightly redesigning the look and feel of said banner component).
The modal allows adjusting job settings same way they can be adjusted
during clone, but available without cloning the original job.

feature(TestRuns): Jenkins Job Configuration Modal

---

argus/backend/plugins/sct/service.py

This change changes the current "COREDUMP-{whatever it is in the node
name in sct" into "core.scylla-{node_instance_name}.gz"

improvement(plugins/sct): Use different naming scheme for coredump links

---

argus/backend/service/argus_service.py

This commit adds another read batching into assignee retrieval, as they
can also overflow cartesian product setting.

fix(argus_service): Batch query schedules as well

---

argus/backend/service/views.py

This commit makes it so that any item returned by search that is
disabled is removed from the resulting set

improvement(service/views): Ignore disabled tests/groups/releases

---

docs/dev-setup.md

Added link to sample argus data on our s3 bucket

improvement(docs): Add sample data s3 link

---

argus/backend/service/user.py

Fixes an issue where server would return 500 for non-logged in users.

fix(service/user): Check if user is None

---

frontend/Common/TestStatus.js
frontend/TestRun/ResultsTab.svelte

In case some columns/rows are missing table breaks (wrong data in columns or looks just bad).
Fix by revamping the way we pass data to renderer: transform it to more organized data structure with known columns and rows that are present and properly handling missing values.
fixes: https://github.com/scylladb/argus/issues/417

fix(results): fix results tables when missing data

---

argus/backend/service/testrun.py
frontend/TestRun/ResultsTab.svelte

In case we have multiple tables, their order is random.
Added ordering based on which table values were inserted first.
Results were having to little margins and looking too messy.
Added filtering capabilities, increased margins and shown a vertical bar
on the left side of each table with color based on results (red if any
result was failed).

fix(results): Fix results ordering and visibility

---

frontend/TestRun/ResultsTab.svelte

Users might want to put resutls into gh issues. Added a copy to markdown button in the corner of all results tables for easy copy it in a way that can be pasted to gh issue. When copy happens, info message appears to give a clear sign about it.
closes: https://github.com/scylladb/argus/issues/421

improvement(results): add copy button to tables

---

argus/backend/plugins/sct/testrun.py

In upgrade tests results should be mapped to upgraded scylla version instead of base one.
Fixed by first getting `scylla-server-upgraded` package date and only fallback to `scylla-server` when not available.
Also fixed issue with timestamp stored in db on local env.

fix(results): fix sut_date for upgrade tests

---

docs/generic_results.md

Needed to update TEXT field support and add a few clarifications.

improvement(docs): improved and updated docs for generic results

---

argus/client/generic_result.py
pyproject.toml

ValidationRules are optional and should not break the code when not provided.

fix(client): don't require ValidationRules in results tables

---

frontend/TestRun/TestRunInfo.svelte

fixes: 	https://github.com/scylladb/argus/issues/464

fix(key-name): sct runner ssh key changed - updating

---

argus/backend/tests/conftest.py
argus/backend/tests/results_service/test_best_results.py
argus/backend/tests/results_service/test_validation_rules.py

Some test files were missing from previous commit. Added.

fix(tests): add missing test files

---

argus/backend/service/testrun.py

This commit fixes an issue where a user with limited repo access (due to
user permission settings) was unable to submit (attach) a new issue to
a test run. This was due to submit endpoint expecting to be able to read
title of the submitted issue and save that. This is now done on
best-effort basis and the fallback title is now just "owner/repo#N"
Fixes #435

fix(service/testrun): Allow limited gh token to submit issues

---

frontend/TestRun/StructuredEvent.svelte

This commit adds a new field for Structured event. If `known_issue`
field is found, a link to it is generated and added to the Event element
Fixes scylladb/qa-tasks#1730

improvement(StructuredEvent.svelte): Add `known_issue` field

---

frontend/TestRun/ResultsGraph.svelte

Show enlarge graph button in right upper corner of each graph to open modal with it on full screen.
closes: https://github.com/scylladb/argus/issues/505
clicking top right corner button will enlarge to full screen in modal (with x to close or pressing esc on keyboard)

improvement(graphs): enlarge graph button

---

frontend/TestRun/ResultsGraph.svelte

When using duration graphs y axis was formatted to numeric value causing confusion and bad UX.
Improvement by reformatting axis/tooltip to be in HH:MM:SS format.
closes: https://github.com/scylladb/argus/issues/544

improvement(graphs): use proper unit for duration graphs

---

frontend/TestRun/ResultsGraphs.svelte

We often need to peek 2 years back for more comprehensive view. Added 1 year and 2 year date filters.

improvement(graphs): add more date filters

---

argus/backend/models/web.py
argus/backend/service/notification_manager.py
argus/backend/service/views_widgets/highlights.py
argus/backend/tests/view_widgets/test_highlights_api.py
frontend/Common/ArgusNotification.ts
frontend/Profile/Notification.svelte
templates/notifications/view_highlight_mention.html.j2
templates/notifications/view_highlight_mention_email.html.j2

Highlights (with action items) now support mentions in content.
closes: https://github.com/scylladb/argus/issues/507

improvement(highlights): support mentions in highlights widget

---

frontend/Views/Widgets/ViewHighlights/ActionItem.svelte

Add users data to comment for proper avatar display.

fix(highlights-view): fix missing avatar in action item comments

---

argus/backend/service/results_service.py

When there are multiple packages related scylla (e.g. scylla-server-target and scylla-server), changes for all of them are counted - making all dots on graph shown as additional package was changed too (scylla-server-target in this example because it changes every run along with scylla-server).
This causes all dot's marked as 'package changed' and user must peek into each to actually see if that's true.
Fixed by removing all additional scylla packages from package list so we have only one on graph.
Solution is not perfect - in upgrade tests, scylla-server-upgrade is used while 'steady state' results are for scylla-server package (measured before upgrade) - in that case steady state results may confuse as hides scylla-server pkg version and show only scylla-server-upgrade. Fixing this is …

fix(graphs): fix packages tracking

---

argus/backend/service/planner_service.py
argus/backend/service/views.py

This commit fixes an issue where a view would be dropped and re-created,
removing user customizations to it. Instead, the view is updated and
user customizations are kept.

fix(service/plans): Update attached views instead of recreating them

---

argus/backend/controller/view_api.py
argus/backend/controller/views_widgets/graphs.py
frontend/Common/ViewTypes.js
frontend/Views/Widgets/GraphsWidget/GraphsWidget.svelte

Introducing Graphs Widget which displays view's tests Graphs Views (added previously in test's graphs window).
closes: https://github.com/scylladb/qa-tasks/issues/1844
See staging performance regression views for review.

feature(view): graphs widget

---

frontend/ReleaseDashboard/AssigneeFilter.svelte
frontend/ReleaseDashboard/TestDashboard.svelte

This commit adds a new filter onto TestDashboard widget, allowing users
to filter groups/tests by assignee, making finding your own jobs easier.
Task: #588

feature(TestDashboard): Add filter by user filter

---

frontend/ReleasePlanner/ReleasePlanCopyForm.svelte
frontend/ReleasePlanner/ReleasePlanCreator.svelte

Some assignee selectors were missing filter function that would allow
them to be filtered by real name of the user.
Fixes #603

fix(ReleasePlanner): Allow searching assignees by Full Name

---

frontend/TestRun/TestRun.svelte
frontend/TestRun/TestRunInfo.svelte
frontend/WorkArea/WorkArea.svelte

This commit adds scrollbars to large tables in case they overflow
horizontal spaces and also disables sidebar inside the WorkArea on small
screens.
Fixes #601

fix(WorkArea): Small screen improvements

---

argus/backend/controller/main.py
frontend/TestRun/DriverMatrixTestRun.svelte
frontend/TestRun/Generic/GenericTestRun.svelte
frontend/TestRun/Sirenada/SirenadaTestRun.svelte
frontend/TestRun/TestRun.svelte
frontend/WorkArea/TestRunDispatcher.svelte
frontend/WorkArea/TestRuns.svelte
frontend/run-by-plugin.js
frontend/test-run-details.js
templates/run_view_by_plugin.html.j2

Added possibility to link to specific tab in TestRun view.
closes: https://github.com/scylladb/argus/issues/604

improvement(TestRun): allow linking to secific tab

---

frontend/TestRun/ResultsGraph.svelte

Added easy and quick way to copy graph as it is currently displayed.
closes: https://github.com/scylladb/argus/issues/506
placed in right upper corner:
visible also when graph is open in modal window

improvement(graphs): add copy graph button

---

frontend/Views/Widgets/ViewHighlights/HighlightItem.svelte

Highlight update didn't work due to missing body.message update.

fix(highlightWidget): fix update highlight

---

pyproject.toml
pytest.ini

No need to have multiple config files

improvement(pytest): Migrate pytest.ini into pyproject.toml

---

frontend/TestRun/Generic/GenericTestRun.svelte
frontend/TestRun/Generic/Subtest.js
frontend/TestRun/Pytest/PytestItem.svelte
frontend/TestRun/Pytest/PytestRun.svelte
frontend/TestRun/Pytest/PytestTab.svelte
frontend/TestRun/Pytest/index.js
frontend/TestRun/Pytest/types.ts
frontend/Utils/IntersectionObserver.svelte
package.json

feature(pytest): pytest results frontend parts

---

README.md

Makes it easier to get to the correct pypi package and shows released version

improvement(readme): Add Pypi badge

---

frontend/TestRun/Jenkins/SCTParameterWizard.svelte

This PR moves Scylla BYO parameters into a wizard. 
Fizes https://github.com/scylladb/argus/issues/667

improvement(SCTParameterWizard): move Scylla BYO params to wizard

---

frontend/TestRun/Jenkins/SCTParameterWizard.svelte

Slightly improve Scylla BYO description

improvement(SCTParameterWizard): update Scylla BYO description

---

argusAI/uv.lock
pyproject.toml
uv.lock

chore(project): Update dependencies

---

frontend/TestRun/EventsTab.svelte

When similar_events endpoint response icludes empty array only, then events tab does not show any event.
Fix by proper handling this case.
fixes: https://github.com/scylladb/argus/issues/743

fix(eventsTab): properly handle empty similar_events response

---

argus_web.example.yaml
templates/partials/nav_bar.html.j2

This commit adds a new user-configurable nav bar element, intended to
act as a link to documentation pages for the application. If the link is
unconfigured, the element is not shown.
Fixes #555

feature(nav_bar.html.j2): Add a configurable Documentation link

---

argus/client/base.py

- Add debug logs for GET requests showing URL and parameters
- Add debug logs for POST requests showing URL, parameters, and body
closes: https://github.com/scylladb/argus/issues/761

improvement(client): Add debug logging for HTTP requests
